import { AlertTriangle, CheckCircle2, CircleHelp, ExternalLink, ShieldCheck, XCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Card, EmptyState, PageHeader, SectionTitle } from '../../components/Ui';
import { useAsyncContent } from '../../hooks/useAsyncContent';
import { loadBuildMissions, loadExecutorContentManifest, loadGuideIndex, loadScriptCatalog } from '../../lib/executorContent';
import { validateSuite } from '../../lib/executorValidation';
import { useExecutorStore } from '../../store/useExecutorStore';
import { useProjectStore } from '../../store/useProjectStore';

export function ExecutorValidationPage(){
  const project=useProjectStore(state=>state.project);const executor=useExecutorStore(state=>state.executor);
  const {data:manifest}=useAsyncContent(loadExecutorContentManifest,[]);const {data:missions}=useAsyncContent(loadBuildMissions,[]);const {data:guides}=useAsyncContent(loadGuideIndex,[]);const {data:scripts}=useAsyncContent(loadScriptCatalog,[]);
  if(!manifest||!missions||!guides||!scripts)return <div className="executor-loading">Executando validação…</div>;
  const findings=validateSuite(project,executor,manifest,missions,guides,scripts);const errors=findings.filter(item=>item.severity==='error').length;const warnings=findings.filter(item=>item.severity==='warning').length;
  return <div><PageHeader title="Validação da Suite" subtitle="Verificação cruzada entre Planejador, Executor, roteiro, guias, scripts, relações e problemas."/><section className={`executor-validation-hero ${errors?'has-errors':'valid'}`}>{errors?<XCircle/>:<ShieldCheck/>}<div><strong>{errors?`${errors} erro(s) estrutural(is)`:'Estrutura consistente'}</strong><span>{warnings} aviso(s) · {findings.length} resultado(s)</span></div></section><div className="executor-validation-list-page">{findings.map(item=><article key={item.id} className={`validation-${item.severity}`}>{item.severity==='error'?<XCircle/>:item.severity==='warning'?<AlertTriangle/>:item.id==='integrity-ok'?<CheckCircle2/>:<CircleHelp/>}<div><span>{item.category}</span><strong>{item.title}</strong><p>{item.detail}</p></div>{item.route&&<Link to={item.route}><ExternalLink/>Abrir</Link>}</article>)}</div>{findings.length===0&&<EmptyState title="Nenhum resultado" text="Não foi possível produzir o relatório de validação."/>}
    <section className="executor-tech-notes"><SectionTitle><ShieldCheck/> Sistemas técnicos confirmados (backup 18/06 att)</SectionTitle><div className="card-grid"><Card><SectionTitle><ShieldCheck/> Vilas sincronizadas</SectionTitle><div className="notice info"><code>Action_RescueNpc</code> usa <code>npcId</code> único, evita contagem duplicada e sincroniza automaticamente a população da vila.</div><ul><li>Resgatados ficam em <code>rescuedCount</code>.</li><li>Lojistas e visitantes usam <code>additionalPopulation</code>.</li><li><code>VillageEvolutionController</code> aplica cinco níveis e reage ao evento oficial.</li></ul></Card><Card><SectionTitle><ShieldCheck/> SaveData versão 1</SectionTitle><p>Ecos disponíveis, total histórico, Melodias Selvagens, IDs de NPCs resgatados, população adicional e snapshots activos são capturados e restaurados.</p><div className="notice info">Saves antigos sem IDs continuam compatíveis por migração, mas devem ser testados antes da entrega.</div></Card><Card><SectionTitle><ShieldCheck/> Jukebox verificado</SectionTitle><p>Não depende de pós-game. Depois da compra única, a lista combina faixas base e Melodias já recolhidas. <code>SyncAllEntries</code> consulta <code>HasCollectedMelody</code> individualmente.</p><ul><li>Abas Normal e Favoritos.</li><li>Favoritos persistidos em GameVariables.</li><li>Actualização em tempo real ao recolher uma Melodia.</li></ul></Card><Card><SectionTitle><AlertTriangle/> Ainda exige configuração</SectionTitle><p>“Implementado” significa que a arquitectura existe. Assets, referências do Inspector, IDs, objectos de cena, música e eventos ainda precisam ser configurados e testados em cada conteúdo real.</p></Card></div></section></div>;
}
