import { useState } from 'react';
import { Download, FileText, Printer } from 'lucide-react';
import { Card, PageHeader, SectionTitle } from '../../components/Ui';
import { useAsyncContent } from '../../hooks/useAsyncContent';
import { loadBuildMissions, loadGuideDocument, loadGuideIndex, loadScriptCatalog, loadScriptDocument } from '../../lib/executorContent';
import { downloadText, safeFileName } from '../../lib/executorExport';
import { getMissionStats, getStepDone } from '../../lib/executorProgress';
import { useExecutorStore } from '../../store/useExecutorStore';

type ReportType='incomplete'|'focus'|'notes'|'issues'|'mission'|'guide'|'script';
export function ExecutorExportPage(){
  const executor=useExecutorStore(state=>state.executor);const {data:missions}=useAsyncContent(loadBuildMissions,[]);const {data:guides}=useAsyncContent(loadGuideIndex,[]);const {data:scripts}=useAsyncContent(loadScriptCatalog,[]);
  const [type,setType]=useState<ReportType>('incomplete');const [selected,setSelected]=useState('');const [format,setFormat]=useState<'md'|'json'>('md');const [busy,setBusy]=useState(false);
  const options=type==='mission'?missions?.map(m=>({id:m.id,label:`${m.number}. ${m.title}`})):type==='guide'?guides?.map(g=>({id:g.slug,label:g.title})):type==='script'?scripts?.files.map(s=>({id:s.id,label:s.filename})):[];
  const exportReport=async()=>{if(!missions)return;setBusy(true);try{let data:unknown;let title='Relatório do Executor';if(type==='incomplete'){title='Steps incompletos';data=missions.filter(m=>m.detailed).flatMap(m=>m.tasks.flatMap(t=>t.steps.filter(s=>!getStepDone(executor,s.id)).map(s=>({missao:m.number,missaoTitulo:m.title,tarefa:t.code,tarefaTitulo:t.title,step:s.index,titulo:s.title,rota:`/executor/roadmap/${m.id}?task=${t.index}&step=${s.index}`}))))}else if(type==='focus'){title='Modo Foco';data=executor.focusItems}else if(type==='notes'){title='Notas do Executor';data=executor.notes}else if(type==='issues'){title='Problemas e limitações';data=executor.issues.filter(i=>i.status!=='resolvido')}else if(type==='mission'){const m=missions.find(item=>item.id===selected);if(!m)throw new Error('Selecione uma missão.');title=`Missão ${m.number} — ${m.title}`;data={...m,progresso:getMissionStats(executor,m),tasks:m.tasks.map(t=>({...t,steps:t.steps.map(s=>({...s,concluido:getStepDone(executor,s.id)}))}))}}else if(type==='guide'){if(!selected)throw new Error('Selecione um guia.');const g=await loadGuideDocument(selected);title=g.title;data={...g,html:undefined,texto:htmlToText(g.html)}}else{if(!selected)throw new Error('Selecione um script.');const s=await loadScriptDocument(selected);title=s.filename;data=s}const date=new Date().toISOString().slice(0,10);if(format==='json')downloadText(`${safeFileName(title)}_${date}.json`,JSON.stringify({title,exportedAt:new Date().toISOString(),data},null,2),'application/json');else downloadText(`${safeFileName(title)}_${date}.md`,toMarkdown(title,data));}finally{setBusy(false)}};
  return <div><PageHeader title="Exportação Seletiva" subtitle="Gere relatórios apenas com o conteúdo necessário, sem exportar todo o banco do Executor." actions={<button className="secondary-button" onClick={()=>window.print()}><Printer/>Imprimir página atual</button>}/><div className="executor-export-layout"><Card><SectionTitle><FileText/> Conteúdo</SectionTitle><label className="field"><span>Tipo de relatório</span><select value={type} onChange={event=>{setType(event.target.value as ReportType);setSelected('')}}><option value="incomplete">Todos os Steps incompletos</option><option value="focus">Lista do Modo Foco</option><option value="notes">Todas as notas</option><option value="issues">Problemas ainda abertos</option><option value="mission">Uma missão de produção</option><option value="guide">Um guia ou tutorial</option><option value="script">Um script</option></select></label>{options&&options.length>0&&<label className="field"><span>Selecionar item</span><select value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Selecione…</option>{options.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label>}<label className="field"><span>Formato</span><select value={format} onChange={event=>setFormat(event.target.value as 'md'|'json')}><option value="md">Markdown legível</option><option value="json">JSON estruturado</option></select></label><button className="primary-button" disabled={busy} onClick={()=>void exportReport()}><Download/>{busy?'Preparando…':'Baixar relatório'}</button></Card><Card><SectionTitle>O que é preservado</SectionTitle><ul className="executor-export-help"><li>IDs e rotas para voltar ao conteúdo.</li><li>Estado de conclusão dos Steps.</li><li>Data e hora da exportação.</li><li>Campos técnicos de guias e scripts quando selecionados.</li><li>O relatório não altera nem apaga o progresso.</li></ul></Card></div></div>;
}
function htmlToText(value:string){const doc=new DOMParser().parseFromString(value,'text/html');return doc.body.textContent?.replace(/\n{3,}/g,'\n\n').trim()||''}
function toMarkdown(title:string,data:unknown){
  const body=Array.isArray(data)
    ? data.map((item,index)=>{const record=isRecord(item)?item:{};const label=String(record.titulo??record.title??record.text??record.id??'Item');return `## ${index+1}. ${label}\n\n\`\`\`json\n${JSON.stringify(item,null,2)}\n\`\`\``}).join('\n\n')
    : typeof data==='string'?data:`\`\`\`json\n${JSON.stringify(data,null,2)}\n\`\`\``;
  return `# ${title}\n\nExportado em ${new Date().toLocaleString('pt-BR')}.\n\n${body}\n`;
}
function isRecord(value:unknown):value is Record<string,unknown>{return typeof value==='object'&&value!==null&&!Array.isArray(value)}
