import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Image, Plus } from 'lucide-react';
import { Card, EmptyState, Field, PageHeader, SectionTitle, StatusBadge, WarningDot } from '../components/Ui';
import { useProjectStore } from '../store/useProjectStore';
import { EntityTools } from '../components/EntityTools';
import { mediaDisplayUrl, persistMediaFile } from '../lib/storage';
import type { EnemyDef, EntityStatus } from '../types';

const CATEGORIES=['Drone','Torreta','Armadilha','Robô Terrestre','Máquina Aquática','Hazard Móvel','Orgânico Corrompido','Mini-boss'];
const MOVEMENTS=['Estático','Patrulha terrestre','Patrulha aérea','Persegue','Foge','Trilho','Superfície da água','Subaquático','Salta','Teleporta'];
const ATTACKS=['Sem ataque','Contato','Corpo a corpo','Investida','Empurrão','Puxão/anzol','Projétil reto','Projétil em arco','Projétil teleguiado','Laser','Área persistente','Rede/armadilha','Invoca outro inimigo'];
const METHODS=['Dano direto','Atingir ponto fraco','Empurrar para hazard','Derrubar em buraco','Fazer cair na água','Tirar da água','Refletir projétil','Usar ataque de outro inimigo','Desligar fonte/alimentação','Congelar','Prender com Resina','Adormecer','Atordoar','Usar como peça do puzzle'];
const ELEMENTS=['Impacto','Corte/Garra','Mordida','Investida','Coice','Rodopio','Explosão/Bomba','Fogo','Gelo','Água/Corrente','Vento','Eletricidade','Queda','Esmagamento','Empurrão','Puxão','Atordoamento','Sono','Resina Antiga','Furtividade'];
const PUZZLES=['Pode ser empurrado','Pode ser puxado','Pode ser congelado','Pode ser preso no chão','Pode dormir','Pode ser ignorado por furtividade','Pode ser atordoado','Pode ser virado','Pode virar plataforma','Pode pressionar placa','Pode ativar botão','Pode bloquear laser','Pode destruir objetos ao atacar','Pode ferir outros inimigos','Recebe dano de hazards'];
const ICONS=['◆','◉','▣','▲','✦','⬡','⌾','✹','⚙','◈','⬢','✚'];

export function EnemiesPage(){
  const project=useProjectStore(s=>s.project);const mutate=useProjectStore(s=>s.mutate);const [params]=useSearchParams();const [selectedId,setSelectedId]=useState(project.enemies.find(e=>!e.archived)?.id);const [filter,setFilter]=useState('todos');
  useEffect(()=>{const id=params.get('entity');if(id)setSelectedId(id)},[params]);
  const enemies=useMemo(()=>project.enemies.filter(e=>!e.archived&&(filter==='todos'||e.status===filter)),[project.enemies,filter]);const enemy=project.enemies.find(e=>e.id===selectedId&&!e.archived);
  const createEnemy=()=>{const id=`inimigo-${Date.now()}`;const next:EnemyDef={id,name:'Novo inimigo',category:'Drone',movement:'Estático',attackStyle:['Sem ataque'],isFlying:false,canSwim:false,canDive:false,defeatMethods:[],weaknesses:[],resistances:[],immunities:[],puzzleTraits:[],icon:'◆',notes:'',status:'planejado',archived:false};mutate(d=>d.enemies.push(next));setSelectedId(id)};
  const update=(fn:(e:EnemyDef)=>void)=>mutate(d=>{const e=d.enemies.find(x=>x.id===selectedId);if(e)fn(e)});
  const relatedPlacements=enemy?project.maps.flatMap(m=>m.objects.filter(o=>o.resourceType==='enemy'&&o.resourceId===enemy.id).map(o=>({areaId:m.areaId,objectId:o.id}))):[];
  const effectiveAnimals=enemy?project.animals.filter(a=>a.canAttack&&(enemy.weaknesses.length===0||a.attackTags.some(tag=>enemy.weaknesses.some(w=>normal(w).includes(normal(tag))||normal(tag).includes(normal(w)))))):[];
  const ineffectiveAnimals=enemy?project.animals.filter(a=>a.canAttack&&a.attackTags.some(tag=>enemy.immunities.some(w=>normal(w).includes(normal(tag))||normal(tag).includes(normal(w))))):[];

  return <div><PageHeader title="Inimigos" subtitle="Cadastre apenas comportamentos relevantes ao planejamento. Inimigos podem ser adicionados em qualquer área e em qualquer quantidade." actions={<button className="primary-button" onClick={createEnemy}><Plus/> Novo inimigo</button>}/>
    <div className="split-editor"><aside className="entity-list"><div className="filter-row"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="todos">Todos os estados</option><option value="planejado">Planejados</option><option value="unity">Configurados no Unity</option><option value="erro">Com erro</option></select></div>{enemies.map(e=><button className={selectedId===e.id?'active':''} key={e.id} onClick={()=>setSelectedId(e.id)}><span className="enemy-list-icon">{e.icon}</span><div><strong>{e.name}</strong><small>{e.category} · {e.movement}</small></div>{e.weaknesses.length+e.puzzleTraits.length===0?<WarningDot title="Sem fraquezas, vantagens ou função de puzzle"/>:<StatusBadge status={e.status}/>}</button>)}</aside>
      <section className="editor-pane">{!enemy?<EmptyState title="Nenhum inimigo selecionado" text="Crie um inimigo global para depois adicioná-lo às áreas e aos mapas."/>:<>
        <div className="editor-heading"><div className="enemy-title"><span className="enemy-big-icon">{enemy.icon}</span><input className="title-input" value={enemy.name} onChange={e=>update(x=>{x.name=e.target.value})}/></div></div>
        <div className="form-grid three"><Field label="Tipo"><select value={enemy.category} onChange={e=>update(x=>{x.category=e.target.value})}>{CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Movimento"><select value={enemy.movement} onChange={e=>update(x=>{x.movement=e.target.value})}>{MOVEMENTS.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Estado"><select value={enemy.status} onChange={e=>update(x=>{x.status=e.target.value as EntityStatus})}><option value="planejado">Planejado</option><option value="unity">Configurado no Unity</option><option value="erro">Erro no Unity</option></select></Field></div>
        <div className="form-grid three"><Field label="Locomoção"><div className="vertical-checks"><label><input type="checkbox" checked={enemy.isFlying} onChange={e=>update(x=>{x.isFlying=e.target.checked})}/> Voador</label><label><input type="checkbox" checked={enemy.canSwim} onChange={e=>update(x=>{x.canSwim=e.target.checked})}/> Nada na superfície</label><label><input type="checkbox" checked={enemy.canDive} onChange={e=>update(x=>{x.canDive=e.target.checked;x.canSwim=x.canSwim||e.target.checked})}/> Mergulha</label></div></Field><Field label="Ícone do mapa"><div className="icon-picker">{ICONS.map(i=><button key={i} className={enemy.icon===i?'selected':''} onClick={()=>update(x=>{x.icon=i})}>{i}</button>)}</div></Field><Field label="Arte conceitual"><label className="mini-upload"><input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f){const saved=await persistMediaFile(f,'enemies');update(x=>{x.image=saved})}}}/>{enemy.image?<img src={mediaDisplayUrl(enemy.image)} alt={`Arte de ${enemy.name}`}/>:<><Image/><span>Adicionar imagem</span></>}</label></Field></div>
        <Card><SectionTitle>Como ataca</SectionTitle><ChoiceGrid values={ATTACKS} selected={enemy.attackStyle} onToggle={v=>update(x=>{x.attackStyle=toggle(x.attackStyle,v)})}/></Card>
        <Card><SectionTitle>Como derrotar ou neutralizar</SectionTitle><ChoiceGrid values={METHODS} selected={enemy.defeatMethods} onToggle={v=>update(x=>{x.defeatMethods=toggle(x.defeatMethods,v)})}/></Card>
        <div className="three-column"><Card><SectionTitle>Fraquezas</SectionTitle><p className="muted">Recebe vantagem deste elemento ou método.</p><ChoiceGrid compact values={ELEMENTS} selected={enemy.weaknesses} onToggle={v=>update(x=>{x.weaknesses=toggle(x.weaknesses,v)})}/></Card><Card><SectionTitle>Resistências</SectionTitle><p className="muted">Funciona, mas com menor efeito.</p><ChoiceGrid compact values={ELEMENTS} selected={enemy.resistances} onToggle={v=>update(x=>{x.resistances=toggle(x.resistances,v)})}/></Card><Card><SectionTitle>Imunidades</SectionTitle><p className="muted">Não é afetado.</p><ChoiceGrid compact values={ELEMENTS} selected={enemy.immunities} onToggle={v=>update(x=>{x.immunities=toggle(x.immunities,v)})}/></Card></div>
        <Card><SectionTitle>Funções de puzzle</SectionTitle><ChoiceGrid values={PUZZLES} selected={enemy.puzzleTraits} onToggle={v=>update(x=>{x.puzzleTraits=toggle(x.puzzleTraits,v)})}/></Card>
        <div className="two-column"><Card><SectionTitle>Animais provavelmente eficazes</SectionTitle><div className="chips">{effectiveAnimals.length?effectiveAnimals.map(a=><span key={a.id}>{a.name}</span>):<span>Qualquer animal que ataque</span>}</div></Card><Card><SectionTitle>Animais sem efeito provável</SectionTitle><div className="chips">{ineffectiveAnimals.length?ineffectiveAnimals.map(a=><span key={a.id}>{a.name}</span>):<span>Nenhuma incompatibilidade marcada</span>}</div></Card></div>
        <Field label="Notas de comportamento"><textarea value={enemy.notes} onChange={e=>update(x=>{x.notes=e.target.value})}/></Field>
        <Card><SectionTitle>Uso no projeto</SectionTitle><p>{relatedPlacements.length} instância(s) colocada(s) em mapas.</p><div className="chips">{[...new Set(relatedPlacements.map(p=>project.areas.find(a=>a.id===p.areaId)?.name).filter(Boolean))].map(name=><span key={name}>{name}</span>)}</div></Card>
        <EntityTools entityRef={{type:'enemy',id:enemy.id}} onArchived={()=>setSelectedId(undefined)}/>
      </>}</section></div>
  </div>
}
function ChoiceGrid({values,selected,onToggle,compact=false}:{values:string[];selected:string[];onToggle:(v:string)=>void;compact?:boolean}){return <div className={`choice-grid ${compact?'compact':''}`}>{values.map(v=><label key={v} className={selected.includes(v)?'selected':''}><input type="checkbox" checked={selected.includes(v)} onChange={()=>onToggle(v)}/><span>{v}</span></label>)}</div>}
function toggle(values:string[],v:string){return values.includes(v)?values.filter(x=>x!==v):[...values,v]}
function normal(s:string){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
