import { useEffect } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { BookOpen, Boxes, CircleHelp, ExternalLink, Map, Music, Network, PawPrint, ScrollText, Settings, UsersRound, Wrench } from 'lucide-react';
import { Card, PageHeader, SectionTitle } from '../components/Ui';

const sections=[
  {id:'primeiros-passos',icon:BookOpen,title:'Primeiros passos',text:'Use o menu lateral para abrir uma biblioteca. Clique numa ficha para editar; mudanças são salvas automaticamente. Ctrl+K abre a busca global e o botão Voltar retorna exatamente à última página visitada.',fields:['Status Planejado: existe apenas no projeto.','Unity: já foi configurado no jogo.','Erro: foi criado no Unity, mas precisa de correção.','Detalhes técnicos ficam fechados por padrão.']},
  {id:'terra-gaia',icon:Network,title:'Terra de Gaia',text:'Arraste uma área da biblioteca esquerda para o canvas. Para ligar, segure um conector amarelo e solte sobre outro nó. Selecione uma linha e pressione Delete ou clique com o botão direito. Resetar mapa original restaura nós e ligações, preservando imagens e desenhos.',fields:['Nós: áreas colocadas.','Ligações: caminhos percorridos pela bola de luz.','Automático: vilas e Provações de Apolo.','Missão principal: áreas de boss.']},
  {id:'mapa-area',icon:Map,title:'Mapa da área',text:'Recursos ficam à esquerda; Inspector e Camadas ficam à direita. A ferramenta Água possui as formas Retangular e Circular. Crie recursos na ficha da área antes de os posicionar.',fields:['Zona: divisão lógica da fase.','Ponto de missão: círculo ligado a missão e tarefa.','Saída: pode apontar para outra área/Terra de Gaia.','Estado visual: Planejado, Unity ou Erro.']},
  {id:'animais-agua',icon:PawPrint,title:'Animais, água e oxigénio',text:'Cada animal pode nadar na superfície, mergulhar com oxigénio limitado, nadar livremente ou afundar. Formas que não sabem nadar devem avisar isso no tutorial do animal. Íris Base é protegida e serve de fallback quando todas as formas animais estão bloqueadas.',fields:['Nado de superfície: permite deslocamento horizontal sem mergulho.','Mergulho terrestre: usa mini-HUD de oxigénio.','Estilo de curva: direto, arco curto ou arco longo.','Afunda: morte e retorno ao último checkpoint.']},
  {id:'provacoes',icon:ScrollText,title:'Provações de Gaia e de Apolo',text:'Provações de Gaia são desafios opcionais. Podem exigir animal, categoria, tempo, derrotar inimigos, coletar todas as Sementes ou um objeto específico. Provações de Apolo são áreas separadas, uma por mundo, desbloqueadas no 100% desse mundo.',fields:['Animal exigido: portal mostra ícone e só acende quando válido.','Bloquear troca: mantém a mesma forma dentro da prova.','Indicador concluído: muda o portal após sucesso.','Apolo: uma Runa por mundo; seis concedem o Emblema de Apolo.']},
  {id:'npc-actions',icon:UsersRound,title:'Eventos de NPC',text:'Planeje ações de mostrar Sementes, animar ganhos/perdas, alterar silenciosamente, guardar/restaurar status, bloquear formas e mostrar tutoriais. O backup 18/06 att já liga resgate, população e evolução da vila. Use npcId único nos resgates e população adicional para lojistas ou visitantes.',fields:['Animação de Sementes: máximo de 1 segundo.','Snapshot: use uma chave única; snapshots activos persistem no save até serem restaurados ou descartados.','Bloqueio de formas: os animais ficam cinzentos; não são removidos.','População da vila: resgatados e habitantes adicionais são guardados separadamente.']},
  {id:'itens-lojas',icon:Boxes,title:'Itens, pickups e lojas',text:'Use Comportamento para separar itens de efeito imediato, inventário, colecionáveis e upgrades. Compras únicas ficam bloqueadas e são enviadas ao fim da lista da loja.',fields:['Broto de Vida: cura imediatamente no chão.','Seiva Vital: comprada, guardada e usada manualmente.','Jukebox: compra única e disponível em qualquer mundo.','Melodia Selvagem: uma por fase e conta para 100%.']},
  {id:'musica',icon:Music,title:'Músicas e Jukebox',text:'As fichas de todas as áreas, vilas, bosses, Provações de Apolo e Terra de Gaia já existem. Adicione apenas o arquivo. Repetir e Fixar ficam na barra musical superior.',fields:['Fixar: mantém a faixa ao navegar.','Repetir: reinicia a faixa ao terminar.','Melodia Selvagem: usa melodyId individual, só aparece depois da recolha e conta para 100%.','Jukebox: compra única, sem requisito de pós-game, com favoritos persistentes.']},
  {id:'mecanicas-ia',icon:Wrench,title:'Mecânicas e IA',text:'Exporte a Base para IA para enviar regras, mundos, animais, itens e ideias existentes. Importe o JSON devolvido. Em conflitos, o programa mantém a mecânica atual por padrão.',fields:['Nova à esquerda: conteúdo do arquivo importado.','Existente à direita: ficha já salva.','Manter existente: opção segura padrão.','Substituir: aplica a versão importada conscientemente.']},
  {id:'idiomas',icon:Settings,title:'Idiomas',text:'A infraestrutura prevê English, Português, Español, Français e 日本語. Apenas Português está habilitado agora. A escolha futura será persistida e o sistema detectará o idioma do computador/Switch.',fields:['Projeto atual: Português.','Fallback futuro: English para idiomas não suportados.','Menus: seletor no menu inicial e no menu +.','HUD: textos devem usar chaves localizáveis, nunca texto fixo no script.']},
];

export function HelpPage(){const location=useLocation();useEffect(()=>{const id=location.hash.slice(1);if(!id)return;requestAnimationFrame(()=>document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'}));},[location.hash]);return <div className="page-stack help-page"><PageHeader title="Ajuda" subtitle="Guia de campos e fluxos do Animals — Planejador." actions={<Link className="secondary-button" to="/whats-new"><ExternalLink/> O que há de novo</Link>}/><div className="help-index">{sections.map(({id,icon:Icon,title})=><a key={id} href={`#${id}`}><Icon/>{title}</a>)}</div>{sections.map(({id,icon:Icon,title,text,fields})=><Card key={id} className="help-section"><span id={id} className="anchor-target"/><SectionTitle><Icon/> {title}</SectionTitle><p>{text}</p><div className="help-fields">{fields.map(field=>{const [name,desc]=field.split(': ');return <div key={field}><strong>{name}</strong><span>{desc}</span></div>})}</div></Card>)}<Card><SectionTitle><CircleHelp/> Regra de segurança</SectionTitle><p>Arquivar envia o elemento à Lixeira e preserva relações. Excluir definitivamente remove referências apenas depois de confirmação.</p></Card></div>}
