import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { Stage, Layer, Rect, Circle, Line, Text, Group, Transformer, Image as KonvaImage } from 'react-konva';
import useImage from 'use-image';
import type Konva from 'konva';
import {
  ArrowDown, ArrowRight, ArrowUp, Copy, Download, Focus, Fullscreen,
  Grid3X3, Group as GroupIcon, Hand, ImagePlus, Layers, Lock, MapPin, MousePointer2, Paintbrush,
  Redo2, Save, Trash2, Type, Undo2, Unlock, Waves, ZoomIn, ZoomOut,
} from 'lucide-react';
import { HelpTip, PageHeader, WarningDot } from '../components/Ui';
import { EntityTools } from '../components/EntityTools';
import { useProjectStore } from '../store/useProjectStore';
import { mediaDisplayUrl, persistMediaFile } from '../lib/storage';
import type { AreaResourceDef, EntityStatus, MapBackgroundImage, MapDocument, MapObject, MapTool } from '../types';

const CATEGORY_COLORS: Record<string,string>={enemy:'#ef6b67',npc:'#73b7ff',rune:'#e5bc53',whisper:'#74d3b0',chest:'#c99764',fragment:'#d478ff',challenge:'#ff8f52',mechanic:'#a7d96b',mission:'#f08bd7'};
const STATUS_COLORS: Record<EntityStatus,string>={planejado:'#4ba3ff',unity:'#4fc279',erro:'#ff5f62'};
const GROUND_COLORS=['#475744','#665845','#4f4f55','#6b4f46','#6b654d','#3e5a56','#505b6e','#704f5f'];
type EditorTool=MapTool|'draw';

export function MapEditorPage(){
  const {areaId}=useParams();const [searchParams]=useSearchParams();
  const project=useProjectStore(s=>s.project),updateMap=useProjectStore(s=>s.updateMap),mutate=useProjectStore(s=>s.mutate),undoMap=useProjectStore(s=>s.undoMap),redoMap=useProjectStore(s=>s.redoMap),flushSave=useProjectStore(s=>s.flushSave);
  const area=project.areas.find(a=>a.id===areaId),world=project.worlds.find(w=>w.id===area?.worldId),map=project.maps.find(m=>m.areaId===areaId);
  const rootRef=useRef<HTMLDivElement|null>(null),canvasRef=useRef<HTMLDivElement|null>(null),stageRef=useRef<Konva.Stage|null>(null),trRef=useRef<Konva.Transformer|null>(null);
  const [size,setSize]=useState({w:1000,h:720}),[tool,setTool]=useState<EditorTool>('select'),[groundColor,setGroundColor]=useState(GROUND_COLORS[0]),[selectedIds,setSelectedIds]=useState<string[]>([]),[draft,setDraft]=useState<MapObject|null>(null),[zonePoints,setZonePoints]=useState<number[]>([]),[arrowStart,setArrowStart]=useState<{x:number;y:number}|null>(null),[drawPoints,setDrawPoints]=useState<number[]>([]),[drawColor,setDrawColor]=useState('#e5bc53'),[resourceTab,setResourceTab]=useState<'area'|'global'>('area'),[pendingResource,setPendingResource]=useState<ResourceLibraryItem|null>(null),[fullscreen,setFullscreen]=useState(false),[exportOpen,setExportOpen]=useState(false),[statusFilter,setStatusFilter]=useState<Record<EntityStatus,boolean>>({planejado:true,unity:true,erro:true}),[selectedBgId,setSelectedBgId]=useState<string>(),[waterShape,setWaterShape]=useState<'waterRect'|'waterCircle'>('waterRect');
  useEffect(()=>{if(!canvasRef.current)return;const ob=new ResizeObserver(([e])=>setSize({w:Math.max(600,e.contentRect.width),h:Math.max(500,e.contentRect.height)}));ob.observe(canvasRef.current);return()=>ob.disconnect()},[]);
  useEffect(()=>{const h=()=>setFullscreen(document.fullscreenElement===rootRef.current);document.addEventListener('fullscreenchange',h);return()=>document.removeEventListener('fullscreenchange',h)},[]);
  const zones=useMemo(()=>map?.objects.filter(o=>o.type==='zone'&&!o.archived&&o.placed!==false)??[],[map]);
  const visibleObjects=useMemo(()=>map?.objects.filter(o=>!o.archived&&o.placed!==false&&(map.layers[layerFor(o)]?.visible??true)&&(!o.status||statusFilter[o.status]))??[],[map,statusFilter]);
  const resources=useMemo(()=>buildResourceLibrary(project,areaId??'',map?.objects??[]),[project,areaId,map]);
  const selected=map?.objects.find(o=>o.id===selectedIds.at(-1));
  const selectedBg=map?.backgroundImages?.find(b=>b.id===selectedBgId);
  const hasEntry=map?.objects.some(o=>o.type==='entry'&&!o.archived&&o.placed!==false);
  const worldPoint=useCallback(()=>{const st=stageRef.current,p=st?.getPointerPosition();if(!st||!p)return{x:0,y:0};return{x:(p.x-st.x())/st.scaleX(),y:(p.y-st.y())/st.scaleY()}},[]);
  const snap=(v:number)=>Math.round(v/(map?.gridSize??32))*(map?.gridSize??32);
  const point=()=>{const p=worldPoint();return{x:snap(p.x),y:snap(p.y)}};
  const pushObject=(object:MapObject)=>updateMap(areaId!,m=>{object.zIndex=nextZ(m);m.objects.push(object)});
  const patchObject=(id:string,patch:Partial<MapObject>,record=true)=>updateMap(areaId!,m=>{const o=m.objects.find(x=>x.id===id);if(o)Object.assign(o,patch)},record);
  const removeFromMap=(id:string)=>updateMap(areaId!,m=>{const o=m.objects.find(x=>x.id===id);if(o)o.placed=false});
  const hardRemove=(id:string)=>updateMap(areaId!,m=>{m.objects=m.objects.filter(o=>o.id!==id)});
  const selectObject=(id:string,e?:Konva.KonvaEventObject<MouseEvent>)=>{const multi=Boolean(e?.evt.shiftKey);setSelectedBgId(undefined);setSelectedIds(prev=>multi?(prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]):[id])};
  useEffect(()=>{const nodes=selectedIds.map(id=>stageRef.current?.findOne(`#${safeId(id)}`)).filter(Boolean) as Konva.Node[];if(nodes.length&&trRef.current){trRef.current.nodes(nodes);trRef.current.getLayer()?.batchDraw()}else trRef.current?.nodes([])},[selectedIds,map?.objects]);

  const addBackground=async(file:File)=>{const saved=await persistMediaFile(file,`areas/${areaId}/backgrounds`);const c=screenCenter(stageRef.current,size);const bg:MapBackgroundImage={id:crypto.randomUUID(),filePath:saved,x:c.x-300,y:c.y-200,width:600,height:400,opacity:.55,rotation:0,locked:false,name:file.name};mutate(d=>d.maps.find(m=>m.areaId===areaId)?.backgroundImages?.push(bg),false,`map-bg:${areaId}`);setSelectedBgId(bg.id);setSelectedIds([])};
  const createMissionPointAt=(x:number,y:number)=>{const name=prompt('Nome do ponto de missão','Novo ponto de missão')?.trim();if(!name)return;const resourceId=`missionPoint-${crypto.randomUUID()}`,objectId=`map-${resourceId}`;mutate(d=>{d.areaResources.push({id:resourceId,areaId:areaId!,kind:'missionPoint',name,description:'Criado diretamente no editor do mapa.',status:'planejado',mapObjectId:objectId,notes:'',archived:false});d.maps.find(m=>m.areaId===areaId)?.objects.push({id:objectId,type:'missionPoint',x,y,label:name,resourceType:'mission',resourceId,icon:'●',status:'planejado',categoryColor:'#ffc857',placed:true,relationIds:[],zIndex:nextZ(d.maps.find(m=>m.areaId===areaId))})},false,`mission-point-map:${areaId}`);setTool('select');setSelectedIds([objectId])};
  const onPointerDown=()=>{if(!map||!areaId)return;const p=point();if(['select','hand','eraseGround','eraseResource'].includes(tool))return;if(tool==='zone'){setZonePoints(v=>[...v,p.x,p.y]);return}if(tool==='arrow'){if(!arrowStart){setArrowStart(p);return}pushObject({id:crypto.randomUUID(),type:'arrow',x:0,y:0,points:[arrowStart.x,arrowStart.y,p.x,p.y],label:'Fluxo',fill:'#d7e0e8',placed:true});setArrowStart(null);return}if(tool==='entry'){const existing=map.objects.find(o=>o.type==='entry');if(existing)patchObject(existing.id,{x:p.x,y:p.y,placed:true},true);else pushObject({id:crypto.randomUUID(),type:'entry',x:p.x,y:p.y,label:'Entrada',icon:'⇥',fill:'#68d391',placed:true});setTool('select');return}if(tool==='missionPoint'){createMissionPointAt(p.x,p.y);return}if(tool==='text'){const text=prompt('Texto da anotação','Nota de level design')?.trim();if(text)pushObject({id:crypto.randomUUID(),type:'note',x:p.x,y:p.y,label:text,fill:'#f5e7a1',placed:true});setTool('select');return}if(tool==='draw'){setDrawPoints([p.x,p.y]);return}if(tool==='resource'&&pendingResource){placeResource(p.x,p.y,pendingResource);return}if(['ground','waterRect','waterCircle'].includes(tool)){const shapeType:MapObject['type']=tool==='ground'?'ground':tool==='waterRect'?'waterRect':'waterCircle';setDraft({id:crypto.randomUUID(),type:shapeType,x:p.x,y:p.y,width:map.gridSize,height:map.gridSize,radius:map.gridSize,fill:tool==='ground'?groundColor:'#3f9ad8',opacity:tool==='ground'?1:.38,placed:true})}};
  const onPointerMove=()=>{const p=point();if(draft){if(draft.type==='waterCircle')setDraft({...draft,radius:Math.max(map?.gridSize??32,Math.hypot(p.x-draft.x,p.y-draft.y))});else setDraft({...draft,width:p.x-draft.x||map?.gridSize,height:p.y-draft.y||map?.gridSize})}if(tool==='draw'&&drawPoints.length)setDrawPoints(v=>[...v,p.x,p.y])};
  const onPointerUp=()=>{if(draft){pushObject(normalizeRect(draft));setDraft(null)}if(tool==='draw'&&drawPoints.length>3){mutate(d=>d.maps.find(m=>m.areaId===areaId)?.drawings?.push({id:crypto.randomUUID(),points:drawPoints,color:drawColor,width:5}),false,`map-draw:${areaId}`);setDrawPoints([])}};
  const placeResource=(x:number,y:number,item:ResourceLibraryItem)=>{const zoneId=findZoneAt(x,y,zones);const existing=map?.objects.find(o=>o.resourceId===item.id&&o.placed===false);const objectId=existing?.id??`map-${item.id}-${crypto.randomUUID()}`;if(existing)patchObject(existing.id,{x,y,placed:true,zoneId,label:item.label,icon:item.icon,resourceType:item.type,categoryColor:item.color},true);else pushObject({id:objectId,type:item.objectType??(item.type==='mission'?'missionPoint':'resource'),x,y,placed:true,zoneId,resourceType:item.type,resourceId:item.id,icon:item.icon,label:item.label,status:item.status??'planejado',categoryColor:item.color,relationIds:item.relationIds});mutate(d=>{const r=d.areaResources.find(r=>r.id===item.id);if(r){r.mapObjectId=objectId;r.zoneId=zoneId}const c=d.challenges.find(c=>c.id===item.id);if(c)c.portalMapObjectId=objectId},false,`resource-place:${item.id}`);setPendingResource(null);setTool('select');setSelectedIds([objectId])};
  const duplicateSelected=()=>updateMap(areaId!,m=>{const selectedObjects=m.objects.filter(o=>selectedIds.includes(o.id));const clones=selectedObjects.map(o=>({...structuredClone(o),id:crypto.randomUUID(),x:o.x+(m.gridSize||32),y:o.y+(m.gridSize||32),resourceId:undefined,label:`${o.label??'Objeto'} — cópia`,zIndex:nextZ(m)}));m.objects.push(...clones);setSelectedIds(clones.map(c=>c.id))});
  const groupSelected=()=>{const groupId=selectedIds.length>1?`grupo-${crypto.randomUUID()}`:undefined;if(!groupId)return;updateMap(areaId!,m=>m.objects.filter(o=>selectedIds.includes(o.id)).forEach(o=>o.groupId=groupId))};
  const reorder=(direction:'front'|'back')=>updateMap(areaId!,m=>{const selectedSet=new Set(selectedIds);const selected=m.objects.filter(o=>selectedSet.has(o.id));const rest=m.objects.filter(o=>!selectedSet.has(o.id));m.objects=direction==='front'?[...rest,...selected]:[...selected,...rest];m.objects.forEach((o,i)=>o.zIndex=i)});
  const centerMap=()=>{const st=stageRef.current,b=objectBounds(visibleObjects,map?.backgroundImages??[]);if(!st)return;if(!b){st.position({x:size.w/2,y:size.h/2});st.scale({x:1,y:1});return}const scale=Math.max(.1,Math.min(1.6,Math.min((size.w-180)/b.width,(size.h-180)/b.height)));st.scale({x:scale,y:scale});st.position({x:size.w/2-(b.x+b.width/2)*scale,y:size.h/2-(b.y+b.height/2)*scale});st.batchDraw()};
  const centerOnObject=(id:string)=>{const st=stageRef.current,o=map?.objects.find(x=>x.id===id);if(!st||!o)return;st.position({x:size.w/2-o.x*st.scaleX(),y:size.h/2-o.y*st.scaleY()});st.batchDraw()};
  useEffect(()=>{const objectId=searchParams.get('object');if(!objectId||!map)return;const object=map.objects.find(o=>o.id===objectId);if(object?.placed===false)patchObject(object.id,{placed:true,x:0,y:0},true);setSelectedIds([objectId]);window.setTimeout(()=>centerOnObject(objectId),80);
    // The query is intentionally handled only when the map or requested object changes.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  },[searchParams,map?.areaId]);
  const exportPng=()=>{const st=stageRef.current,b=objectBounds(visibleObjects,map?.backgroundImages??[]);if(!st||!b)return alert('O mapa ainda está vazio.');const url=st.toDataURL({x:b.x-60,y:b.y-60,width:b.width+120,height:b.height+120,pixelRatio:2});const a=document.createElement('a');a.href=url;a.download=`animals-${slug(area?.name??'area')}.png`;a.click();setExportOpen(false)};
  useEffect(()=>{const key=(e:KeyboardEvent)=>{const typing=(e.target as HTMLElement)?.matches('input,textarea,select');if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();if(e.shiftKey)redoMap(areaId!);else undoMap(areaId!);return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redoMap(areaId!);return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();duplicateSelected();return}if(typing)return;const k=e.key.toLowerCase();if(k==='v')setTool('select');if(k==='h'||e.code==='Space')setTool('hand');if(k==='g')setTool('ground');if(k==='w')setTool(waterShape);if(k==='z')setTool('zone');if(k==='a')setTool('arrow');if(k==='e')setTool('entry');if(k==='p')setTool('missionPoint');if(k==='t')setTool('text');if(k==='b')setTool('draw');if(k==='f')centerMap();if(e.key==='Delete'){selectedIds.forEach(id=>{const object=map?.objects.find(o=>o.id===id);if(object?.resourceId)removeFromMap(id);else hardRemove(id)});setSelectedIds([])}if(e.key==='Escape'){setDraft(null);setZonePoints([]);setArrowStart(null);setDrawPoints([]);setPendingResource(null);setTool('select')}if(e.key==='Enter'&&zonePoints.length>=6){const name=prompt('Nome da zona',`${slug(area?.name??'area')}-zona${zones.length+1}`)?.trim();if(name)pushObject({id:crypto.randomUUID(),type:'zone',x:0,y:0,points:zonePoints,label:name,fill:world?.theme.primary??'#69a',opacity:.16,placed:true});setZonePoints([]);setTool('select')}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)});
  if(!area||!world||!map)return <div>Mapa não encontrado.</div>;
  return <div ref={rootRef} className={`map-page-v2 ${fullscreen?'is-fullscreen':''}`}>
    {!fullscreen&&<PageHeader title={`Mapa — ${area.name}`} subtitle="Desenhe o greybox, coloque recursos criados e ligue pontos de missão." actions={<><HelpTip topic="mapa-area"/><Link className="secondary-button" to={`/area/${area.id}?tab=resources`}>Recursos da área</Link><button className="secondary-button" onClick={()=>void flushSave()}><Save/> Salvar</button><button className="primary-button" disabled={!hasEntry} onClick={()=>setExportOpen(true)}><Download/> Exportar</button></>}/>} {!hasEntry&&<div className="map-warning"><WarningDot title="Entrada obrigatória ausente"/> Defina a entrada antes da exportação.</div>}
    <div className="map-toolbar"><Tool active={tool==='select'} icon={<MousePointer2/>} label="Selecionar (V)" onClick={()=>setTool('select')}/><Tool active={tool==='hand'} icon={<Hand/>} label="Mão (H)" onClick={()=>setTool('hand')}/><Tool active={tool==='ground'} icon={<Paintbrush/>} label="Chão (G)" onClick={()=>setTool('ground')}/><div className="ground-palette">{GROUND_COLORS.map(c=><button key={c} style={{background:c}} className={groundColor===c?'active':''} onClick={()=>{setGroundColor(c);setTool('ground')}}/>)}</div><div className="water-tool-group"><Tool active={tool==='waterRect'||tool==='waterCircle'} icon={<Waves/>} label="Água (W)" onClick={()=>setTool(waterShape)}/><select aria-label="Forma da água" value={waterShape} onChange={e=>{const shape=e.target.value as 'waterRect'|'waterCircle';setWaterShape(shape);setTool(shape)}}><option value="waterRect">Retangular</option><option value="waterCircle">Circular</option></select></div><Tool active={tool==='zone'} icon={<Grid3X3/>} label="Zona (Z)" onClick={()=>setTool('zone')}/><Tool active={tool==='arrow'} icon={<ArrowRight/>} label="Seta (A)" onClick={()=>setTool('arrow')}/><Tool active={tool==='entry'} icon={<Focus/>} label="Entrada (E)" onClick={()=>setTool('entry')}/><Tool active={tool==='missionPoint'} icon={<MapPin/>} label="Ponto de missão (P)" onClick={()=>setTool('missionPoint')}/><Tool active={tool==='text'} icon={<Type/>} label="Texto (T)" onClick={()=>setTool('text')}/><Tool active={tool==='draw'} icon={<Paintbrush/>} label="Desenho (B)" onClick={()=>setTool('draw')}/><input type="color" value={drawColor} onChange={e=>setDrawColor(e.target.value)}/><label className="tool-button file-button"><input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)void addBackground(f)}}/><ImagePlus/><span>Fundo</span></label><span className="toolbar-divider"/><Tool icon={<Undo2/>} label="Desfazer" onClick={()=>undoMap(area.id)}/><Tool icon={<Redo2/>} label="Refazer" onClick={()=>redoMap(area.id)}/><Tool icon={<Copy/>} label="Duplicar" onClick={duplicateSelected}/><Tool icon={<GroupIcon/>} label="Agrupar" onClick={groupSelected}/><Tool icon={<ArrowUp/>} label="Trazer à frente" onClick={()=>reorder('front')}/><Tool icon={<ArrowDown/>} label="Enviar atrás" onClick={()=>reorder('back')}/><Tool icon={<ZoomOut/>} label="Diminuir" onClick={()=>zoom(stageRef.current,.8)}/><Tool icon={<ZoomIn/>} label="Aumentar" onClick={()=>zoom(stageRef.current,1.25)}/><Tool icon={<Focus/>} label="Centralizar" onClick={centerMap}/><Tool icon={<Fullscreen/>} label="Tela cheia" onClick={()=>fullscreen?void document.exitFullscreen():void rootRef.current?.requestFullscreen()}/></div>
    <div className="map-workspace-v2"><aside className="map-library"><div className="map-panel-title"><strong>Recursos</strong><small>{resources.filter(r=>!r.placed).length} fora do mapa</small></div><div className="mini-tabs"><button className={resourceTab==='area'?'active':''} onClick={()=>setResourceTab('area')}>Da área</button><button className={resourceTab==='global'?'active':''} onClick={()=>setResourceTab('global')}>Globais</button></div><div className="resource-library-list">{resources.filter(r=>resourceTab==='global'?r.global:!r.global).map(r=><button key={`${r.type}-${r.id}-${r.instance}`} className={r.placed?'placed':''} onClick={()=>{setPendingResource(r);setTool('resource')}}><span style={{background:r.color}}>{r.icon}</span><div><strong>{r.label}</strong><small>{r.placed?'Já colocado':'Clique e coloque'}</small></div>{!r.relations&&<WarningDot title="Sem relações"/>}</button>)}</div></aside>
      <div className="map-canvas" ref={canvasRef}><Stage ref={stageRef} width={size.w} height={size.h} x={size.w/2} y={size.h/2} draggable={tool==='hand'} onWheel={e=>wheelZoom(e,stageRef.current)} onMouseDown={onPointerDown} onMouseMove={onPointerMove} onMouseUp={onPointerUp} onClick={e=>{if(e.target===e.target.getStage()&&tool==='select'){setSelectedIds([]);setSelectedBgId(undefined)}}}>
        <Layer visible={map.layers.background?.visible}>{(map.backgroundImages??[]).map(bg=><BackgroundShape key={bg.id} bg={bg} selected={selectedBgId===bg.id} locked={map.layers.background?.locked||bg.locked} onSelect={()=>{setSelectedBgId(bg.id);setSelectedIds([])}} onChange={p=>mutate(d=>{const b=d.maps.find(m=>m.areaId===area.id)?.backgroundImages?.find(x=>x.id===bg.id);if(b)Object.assign(b,p)},false,`map-bg:${bg.id}`)}/>)}</Layer>
        <Layer listening={false}><Grid width={size.w*10} height={size.h*10} grid={map.gridSize}/>{(map.drawings??[]).map(line=><Line key={line.id} points={line.points} stroke={line.color} strokeWidth={line.width} lineCap="round" lineJoin="round"/>)}{drawPoints.length>1&&<Line points={drawPoints} stroke={drawColor} strokeWidth={5} lineCap="round"/>}</Layer>
        <Layer>{[...visibleObjects].sort((a,b)=>(a.zIndex??0)-(b.zIndex??0)).map(o=><MapShape key={o.id} object={o} selected={selectedIds.includes(o.id)} showStatus={map.showStatusOutlines} locked={map.layers[layerFor(o)]?.locked??false} onSelect={e=>selectObject(o.id,e)} onCommit={p=>patchObject(o.id,o.type==='resource'||o.type==='missionPoint'?{...p,zoneId:findZoneAt(p.x??o.x,p.y??o.y,zones)}:p,true)} onErase={()=>{if((tool==='eraseGround'&&['ground','waterRect','waterCircle'].includes(o.type))||(tool==='eraseResource'&&['resource','missionPoint'].includes(o.type)))removeFromMap(o.id)}} currentTool={tool}/>)}{draft&&<MapShape object={draft} selected={false} showStatus={false} locked onSelect={()=>{}} onCommit={()=>{}} onErase={()=>{}} currentTool={tool}/>} {zonePoints.length>=2&&<Line points={zonePoints} stroke={world.theme.primary} strokeWidth={3} dash={[8,6]}/>} {arrowStart&&<Circle x={arrowStart.x} y={arrowStart.y} radius={7} fill="#fff"/>}<Transformer ref={trRef} rotateEnabled/></Layer>
      </Stage><div className="map-help">Shift + clique seleciona vários. Ctrl+D duplica. Pontos, saídas e recursos são criados na ficha da área e arrastados pela biblioteca.</div></div>
      <aside className="map-inspector"><div className="map-panel-title"><strong>Inspector</strong><Layers/></div><StatusFilters value={statusFilter} onChange={setStatusFilter}/>{selected?<Inspector object={selected} areaId={area.id} zones={zones} project={project} onChange={p=>{patchObject(selected.id,p,true);const r=project.areaResources.find(r=>r.id===selected.resourceId);if(r)mutate(d=>{const target=d.areaResources.find(x=>x.id===r.id);if(target){if(p.label!==undefined)target.name=p.label;if(p.status)target.status=p.status;if(p.zoneId!==undefined)target.zoneId=p.zoneId}},false,`resource-sync:${r.id}`)}} onRemove={()=>{removeFromMap(selected.id);setSelectedIds([])}}/>:selectedBg?<BackgroundInspector bg={selectedBg} onChange={p=>mutate(d=>{const b=d.maps.find(m=>m.areaId===area.id)?.backgroundImages?.find(x=>x.id===selectedBg.id);if(b)Object.assign(b,p)},false,`map-bg:${selectedBg.id}`)}/>:<div className="inspector-empty">Selecione um objeto ou imagem.</div>}<LayerControls map={map} update={fn=>updateMap(area.id,fn,false)}/></aside>
    </div>
    <div className="map-footer"><span>V selecionar</span><span>H mão</span><span>P ponto de missão</span><span>T anotação</span><span>B desenho</span><span>Enter fecha zona</span><span>Ctrl+D duplica</span><span>Delete remove</span></div>
    {exportOpen&&<div className="modal-backdrop"><div className="modal-card"><h2>Exportar mapa</h2><p>O recorte usa os limites reais de objetos, desenhos e imagens.</p><div className="modal-actions"><button className="secondary-button" onClick={()=>setExportOpen(false)}>Cancelar</button><button className="primary-button" onClick={exportPng}><Download/> Exportar PNG</button></div></div></div>}
  </div>;
}

type ResourceLibraryItem={type:MapObject['resourceType'];id:string;label:string;icon:string;color:string;placed:boolean;global:boolean;instance:number;relations:boolean;status?:EntityStatus;relationIds?:string[];objectType?:MapObject['type']};
function buildResourceLibrary(project:ReturnType<typeof useProjectStore.getState>['project'],areaId:string,objects:MapObject[]):ResourceLibraryItem[]{const placed=(id:string)=>objects.some(o=>o.resourceId===id&&o.placed!==false&&!o.archived);const list:ResourceLibraryItem[]=[];for(const r of project.areaResources.filter(r=>r.areaId===areaId&&!r.archived)){const type=resourceType(r),meta=resourceMeta(r);list.push({type,id:r.id,label:r.name,icon:meta.icon,color:meta.color,placed:placed(r.id),global:false,instance:list.length,relations:Boolean(r.missionId||r.taskId||r.targetAreaId),status:r.status,relationIds:[r.missionId,r.taskId,r.targetAreaId].filter(Boolean) as string[],objectType:r.kind==='missionPoint'?'missionPoint':r.kind==='levelNote'?'note':r.kind==='exit'?'entry':'resource'})}project.whispers.filter(w=>w.areaId===areaId&&!w.archived).forEach(w=>list.push({type:'whisper',id:w.id,label:w.phrase||'Sussurro',icon:'〰',color:CATEGORY_COLORS.whisper,placed:placed(w.id),global:false,instance:list.length,relations:Boolean(w.sourceNpcId),status:w.status}));project.challenges.filter(c=>c.areaId===areaId&&!c.archived).forEach(c=>list.push({type:'challenge',id:c.id,label:c.name,icon:'◯',color:CATEGORY_COLORS.challenge,placed:placed(c.id),global:false,instance:list.length,relations:Boolean(c.objective),status:c.status}));project.npcs.filter(n=>n.rescueAreaId===areaId&&!n.archived).forEach(n=>list.push({type:'npc',id:n.id,label:n.name,icon:'♟',color:CATEGORY_COLORS.npc,placed:placed(n.id),global:false,instance:list.length,relations:n.missionIds.length>0,status:n.status}));project.mechanics.filter(m=>!m.archived).forEach(m=>list.push({type:'mechanic',id:m.id,label:m.name,icon:m.icon,color:CATEGORY_COLORS.mechanic,placed:false,global:true,instance:list.length,relations:true}));project.enemies.filter(e=>!e.archived).forEach(e=>list.push({type:'enemy',id:e.id,label:e.name,icon:e.icon||'◆',color:CATEGORY_COLORS.enemy,placed:false,global:true,instance:list.length,relations:e.weaknesses.length+e.puzzleTraits.length>0,status:e.status}));return list}
function resourceType(r:AreaResourceDef):MapObject['resourceType']{if(r.kind==='rune')return'rune';if(r.kind==='chest')return'chest';if(r.kind==='fragment')return'fragment';return'mission'}
function resourceMeta(r:AreaResourceDef){return({rune:{icon:'◆',color:'#d9b34c'},chest:{icon:'▣',color:'#b77945'},fragment:{icon:'♥',color:'#e66c79'},missionObject:{icon:'◇',color:'#8a77d6'},missionPoint:{icon:'●',color:'#ffc857'},checkpoint:{icon:'⚑',color:'#70b7e6'},exit:{icon:'⇥',color:'#63c6a3'},safeHaven:{icon:'⌂',color:'#6da7ff'},levelNote:{icon:'T',color:'#e7c76e'},narrativeObject:{icon:'✦',color:'#b882d8'}} as Record<AreaResourceDef['kind'],{icon:string;color:string}>)[r.kind]}
function MapShape({object,selected,showStatus,locked,onSelect,onCommit,onErase,currentTool}:{object:MapObject;selected:boolean;showStatus:boolean;locked:boolean;onSelect:(e:Konva.KonvaEventObject<MouseEvent>)=>void;onCommit:(p:Partial<MapObject>)=>void;onErase:()=>void;currentTool:EditorTool}){const stroke=showStatus&&object.status?STATUS_COLORS[object.status]:selected?'#fff':'#26323c',sw=showStatus&&object.status?4:selected?3:1,draggable=currentTool==='select'&&!locked&&!['zone','arrow'].includes(object.type);const common={id:safeId(object.id),draggable,onClick:(e:Konva.KonvaEventObject<MouseEvent>)=>{e.cancelBubble=true;if(currentTool==='eraseGround'||currentTool==='eraseResource')onErase();else onSelect(e)},onDragEnd:(e:Konva.KonvaEventObject<DragEvent>)=>onCommit({x:e.target.x(),y:e.target.y()})};if(object.type==='ground'||object.type==='waterRect')return <Rect {...common} x={object.x} y={object.y} width={object.width} height={object.height} fill={object.fill} opacity={object.opacity??1} stroke={stroke} strokeWidth={sw} onTransformEnd={e=>{const n=e.target;onCommit({x:n.x(),y:n.y(),width:Math.max(16,n.width()*n.scaleX()),height:Math.max(16,n.height()*n.scaleY())});n.scale({x:1,y:1})}}/>;if(object.type==='waterCircle')return <Circle {...common} x={object.x} y={object.y} radius={object.radius} fill={object.fill} opacity={object.opacity??.4} stroke={stroke} strokeWidth={sw}/>;if(object.type==='zone'&&object.points)return <Group><Line id={safeId(object.id)} points={object.points} closed fill={object.fill} opacity={object.opacity??.18} stroke={selected?'#fff':object.fill} strokeWidth={selected?4:2} onClick={e=>{e.cancelBubble=true;onSelect(e)}}/><Text x={Math.min(...object.points.filter((_,i)=>i%2===0))+8} y={Math.min(...object.points.filter((_,i)=>i%2===1))+8} text={object.label} fill="#fff"/></Group>;if(object.type==='arrow'&&object.points)return <Group><Line id={safeId(object.id)} points={object.points} stroke={selected?'#fff':object.fill??'#fff'} strokeWidth={selected?6:4} hitStrokeWidth={20} onClick={e=>{e.cancelBubble=true;onSelect(e)}}/><Text x={object.points[0]} y={object.points[1]-24} text={object.label} fill="#fff"/></Group>;if(object.type==='note')return <Group {...common} x={object.x} y={object.y}><Rect x={-8} y={-6} width={Math.max(120,(object.label?.length??10)*8)} height={34} fill="#232b30" opacity={.9} cornerRadius={5}/><Text text={object.label??''} fill={object.fill??'#f5e7a1'} fontSize={15}/></Group>;return <Group {...common} x={object.x} y={object.y}><Circle radius={22} fill={object.categoryColor??object.fill??'#6ba'} stroke={stroke} strokeWidth={sw}/><Text text={object.icon??'•'} x={-12} y={-13} width={24} align="center" fill="#10161c" fontSize={22}/><Text text={object.label??''} x={-65} y={28} width={130} align="center" fill="#fff" fontSize={13}/>{(object.relationIds?.length??0)===0&&object.type==='missionPoint'&&<Circle x={18} y={-18} radius={8} fill="#ffba49"/>}</Group>}
function BackgroundShape({bg,selected,locked,onSelect,onChange}:{bg:MapBackgroundImage;selected:boolean;locked:boolean;onSelect:()=>void;onChange:(p:Partial<MapBackgroundImage>)=>void}){const [image]=useImage(mediaDisplayUrl(bg.filePath)??'','anonymous');const ref=useRef<Konva.Image|null>(null),tr=useRef<Konva.Transformer|null>(null);useEffect(()=>{if(selected&&ref.current&&tr.current){tr.current.nodes([ref.current]);tr.current.getLayer()?.batchDraw()}else tr.current?.nodes([])},[selected]);return <><KonvaImage ref={ref} id={`bg_${safeId(bg.id)}`} image={image} x={bg.x} y={bg.y} width={bg.width} height={bg.height} opacity={bg.opacity} rotation={bg.rotation} draggable={!locked} stroke={selected?'#ffffff':undefined} strokeWidth={selected?3:0} onClick={e=>{e.cancelBubble=true;onSelect()}} onDragEnd={e=>onChange({x:e.target.x(),y:e.target.y()})} onTransformEnd={e=>{const n=e.target;onChange({x:n.x(),y:n.y(),width:Math.max(40,n.width()*n.scaleX()),height:Math.max(40,n.height()*n.scaleY()),rotation:n.rotation()});n.scale({x:1,y:1})}}/>{selected&&<Transformer ref={tr} rotateEnabled enabledAnchors={['top-left','top-right','bottom-left','bottom-right']}/>}</>}
function Inspector({object,areaId,zones,project,onChange,onRemove}:{object:MapObject;areaId:string;zones:MapObject[];project:ReturnType<typeof useProjectStore.getState>['project'];onChange:(p:Partial<MapObject>)=>void;onRemove:()=>void}){const resource=project.areaResources.find(r=>r.id===object.resourceId);return <div className="inspector-form"><label>Nome<input value={object.label??''} onChange={e=>onChange({label:e.target.value})}/></label>{object.status&&<label>Estado<select value={object.status} onChange={e=>onChange({status:e.target.value as EntityStatus})}><option value="planejado">Planejado</option><option value="unity">Unity</option><option value="erro">Erro</option></select></label>}<label>Zona<select value={object.zoneId??''} onChange={e=>onChange({zoneId:e.target.value||undefined})}><option value="">Detectar pelo centro</option>{zones.map(z=><option key={z.id} value={z.id}>{z.label}</option>)}</select></label>{resource?.kind==='missionPoint'&&<><label>Missão<select value={resource.missionId??''} onChange={e=>onChange({relationIds:[e.target.value,resource.taskId].filter(Boolean) as string[]})}><option value="">Nenhuma</option>{project.missions.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>{resource.missionId&&<Link className="text-button" to={`/missions?entity=${resource.missionId}&task=${resource.taskId??''}`}>Abrir missão relacionada</Link>}</>} {resource?.kind==='exit'&&resource.targetAreaId&&<Link className="text-button" to={`/area/${resource.targetAreaId}`}>Destino: {project.areas.find(a=>a.id===resource.targetAreaId)?.name}</Link>}<div className="coords"><span>X {Math.round(object.x)}</span><span>Y {Math.round(object.y)}</span></div><button className="secondary-button" onClick={onRemove}><Trash2/> Retirar do mapa</button><EntityTools entityRef={{type:'mapObject',id:object.id,parentId:areaId}}/></div>}
function BackgroundInspector({bg,onChange}:{bg:MapBackgroundImage;onChange:(p:Partial<MapBackgroundImage>)=>void}){return <div className="inspector-form"><label>Nome<input value={bg.name} onChange={e=>onChange({name:e.target.value})}/></label><label>Opacidade<input type="range" min=".05" max="1" step=".05" value={bg.opacity} onChange={e=>onChange({opacity:Number(e.target.value)})}/></label><label>Rotação<input type="number" value={Math.round(bg.rotation)} onChange={e=>onChange({rotation:Number(e.target.value)})}/></label><button className="secondary-button" onClick={()=>onChange({locked:!bg.locked})}>{bg.locked?<Unlock/>:<Lock/>}{bg.locked?' Desbloquear':' Bloquear'}</button></div>}
function LayerControls({map,update}:{map:MapDocument;update:(fn:(m:MapDocument)=>void)=>void}){return <div className="layer-controls"><h3>Camadas</h3>{Object.entries(map.layers).map(([name,state])=><div className="layer-row" key={name}><label><input type="checkbox" checked={state.visible} onChange={e=>update(m=>{m.layers[name].visible=e.target.checked})}/>{name}</label><button className="icon-button" onClick={()=>update(m=>{m.layers[name].locked=!m.layers[name].locked})}>{state.locked?<Lock/>:<Unlock/>}</button></div>)}<label className="check-row"><input type="checkbox" checked={map.showStatusOutlines} onChange={e=>update(m=>{m.showStatusOutlines=e.target.checked})}/> Contornos de estado</label></div>}
function StatusFilters({value,onChange}:{value:Record<EntityStatus,boolean>;onChange:(v:Record<EntityStatus,boolean>)=>void}){return <div className="status-filters"><h3>Filtrar por estado</h3>{(['planejado','unity','erro'] as EntityStatus[]).map(s=><label key={s}><input type="checkbox" checked={value[s]} onChange={e=>onChange({...value,[s]:e.target.checked})}/><span style={{background:STATUS_COLORS[s]}}/>{s}</label>)}</div>}
function Tool({active,icon,label,onClick}:{active?:boolean;icon:React.ReactNode;label:string;onClick:()=>void}){return <button className={`tool-button ${active?'active':''}`} title={label} onClick={onClick}>{icon}<span>{label.split(' (')[0]}</span></button>}
function Grid({width,height,grid}:{width:number;height:number;grid:number}){const lines=[];for(let x=-width/2;x<=width/2;x+=grid)lines.push(<Line key={`x${x}`} points={[x,-height/2,x,height/2]} stroke="#8ca0b3" opacity={x%(grid*5)===0?.16:.07}/>);for(let y=-height/2;y<=height/2;y+=grid)lines.push(<Line key={`y${y}`} points={[-width/2,y,width/2,y]} stroke="#8ca0b3" opacity={y%(grid*5)===0?.16:.07}/>);return <>{lines}</>}
function layerFor(o:MapObject){if(o.type==='ground')return'terrain';if(o.type==='waterRect'||o.type==='waterCircle')return'water';if(o.type==='zone')return'zones';if(o.type==='arrow')return'flow';if(o.type==='note')return'notes';if(o.resourceType)return o.resourceType;return'mission'}
function normalizeRect(o:MapObject){if((o.width??0)<0){o.x+=o.width??0;o.width=Math.abs(o.width??0)}if((o.height??0)<0){o.y+=o.height??0;o.height=Math.abs(o.height??0)}return o}
function findZoneAt(x:number,y:number,zones:MapObject[]){return zones.find(z=>z.points&&pointInPolygon(x,y,z.points))?.id}
function pointInPolygon(x:number,y:number,p:number[]){let inside=false;for(let i=0,j=p.length-2;i<p.length;j=i,i+=2){const xi=p[i],yi=p[i+1],xj=p[j],yj=p[j+1];if(((yi>y)!==(yj>y))&&(x<(xj-xi)*(y-yi)/(yj-yi||1e-9)+xi))inside=!inside}return inside}
function objectBounds(objects:MapObject[],backgrounds:MapBackgroundImage[]){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;const add=(x:number,y:number,w=0,h=0)=>{minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x+w);maxY=Math.max(maxY,y+h)};for(const b of backgrounds)add(b.x,b.y,b.width,b.height);for(const o of objects){if(o.points)for(let i=0;i<o.points.length;i+=2)add(o.points[i],o.points[i+1]);else if(o.radius)add(o.x-o.radius,o.y-o.radius,o.radius*2,o.radius*2);else if(o.width||o.height)add(o.x,o.y,o.width??1,o.height??1);else add(o.x-30,o.y-30,60,60)}return Number.isFinite(minX)?{x:minX,y:minY,width:Math.max(1,maxX-minX),height:Math.max(1,maxY-minY)}:null}
function wheelZoom(e:Konva.KonvaEventObject<WheelEvent>,st:Konva.Stage|null){e.evt.preventDefault();if(!st)return;const old=st.scaleX(),p=st.getPointerPosition()!,m={x:(p.x-st.x())/old,y:(p.y-st.y())/old},next=Math.max(.1,Math.min(4,e.evt.deltaY<0?old*1.1:old/1.1));st.scale({x:next,y:next});st.position({x:p.x-m.x*next,y:p.y-m.y*next})}
function zoom(st:Konva.Stage|null,f:number){if(!st)return;st.scale({x:Math.max(.1,Math.min(4,st.scaleX()*f)),y:Math.max(.1,Math.min(4,st.scaleY()*f))});st.batchDraw()}
function screenCenter(st:Konva.Stage|null,size:{w:number;h:number}){return st?{x:(size.w/2-st.x())/st.scaleX(),y:(size.h/2-st.y())/st.scaleY()}:{x:0,y:0}}
function nextZ(map:MapDocument|undefined){return (map?.objects.reduce((m,o)=>Math.max(m,o.zIndex??0),0)??0)+1}
function safeId(id:string){return `obj_${id.replace(/[^a-zA-Z0-9_-]/g,'_')}`}
function slug(s:string){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
