import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, FileAudio, Link2, Music, Pause, Pin, Play, Plus, Trash2, Upload, Volume2, VolumeX } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { Card, EmptyState, Field, HelpTip, PageHeader, SectionTitle } from '../components/Ui';
import { EntityTools } from '../components/EntityTools';
import { mediaDisplayUrl, mediaFileExists, persistMediaFile } from '../lib/storage';
import { attachmentStorageValue, createPlannerMusicAttachment, hasPlannerMusicAttachment } from '../lib/musicAttachments';
import { useProjectStore } from '../store/useProjectStore';
import type { MusicTrack } from '../types';

export function MusicPage(){
  const project=useProjectStore(s=>s.project);const mutate=useProjectStore(s=>s.mutate);const [params]=useSearchParams();
  const [selectedId,setSelectedId]=useState(project.music.find(m=>!m.archived)?.id);const [previewId,setPreviewId]=useState<string>();const [fileOk,setFileOk]=useState<boolean|undefined>();
  useEffect(()=>{const id=params.get('entity');if(id)setSelectedId(id)},[params]);
  const track=project.music.find(m=>m.id===selectedId&&!m.archived);
  const relatedAreaIds=track?(track.areaIds?.length?track.areaIds:track.areaId?[track.areaId]:[]):[];
  const relatedAreas=project.areas.filter(a=>relatedAreaIds.includes(a.id));
  const update=(fn:(m:MusicTrack)=>void)=>mutate(d=>{const target=d.music.find(x=>x.id===selectedId);if(target)fn(target)},false,`music:${selectedId}`);
  const add=()=>{const id=`musica-${Date.now()}`;mutate(d=>d.music.push({id,title:'Nova música',role:'area',areaIds:[],loop:true,jukeboxVisibility:'fora_jukebox',notes:'',archived:false}),false,'music:create');setSelectedId(id)};
  const upload=async(file:File)=>{const saved=await persistMediaFile(file,'music');update(m=>{if(saved.startsWith('data:')){m.dataUrl=saved;m.filePath=undefined}else{m.filePath=saved;m.dataUrl=undefined}m.attachment=createPlannerMusicAttachment(file)});setFileOk(true)};
  useEffect(()=>{let active=true;if(!track||!hasPlannerMusicAttachment(track)){setFileOk(undefined);return;}void mediaFileExists(attachmentStorageValue(track)).then(ok=>{if(active)setFileOk(ok)});return()=>{active=false}},[track]);
  const villageValidation=useMemo(()=>project.worlds.filter(w=>w.villageId).map(world=>{const roles=['vila_vazia','vila_viva','vila_pos_boss'] as const;const found=roles.map(role=>project.music.find(m=>!m.archived&&m.role===role&&(m.areaIds?.includes(world.villageId!)||m.areaId===world.villageId)));return{world,found,complete:found.every(item=>hasPlannerMusicAttachment(item))}}),[project.worlds,project.music]);
  const toggleArea=(id:string)=>update(m=>{const current=m.areaIds??(m.areaId?[m.areaId]:[]);m.areaIds=current.includes(id)?current.filter(x=>x!==id):[...current,id];m.areaId=m.areaIds[0]});

  return <div><PageHeader title="Músicas" subtitle="Biblioteca global do projeto. O Executor reproduz somente os arquivos de áudio anexados aqui às fichas de Música." actions={<div className="inline-actions"><HelpTip topic="musica"/><button className="primary-button" onClick={add}><Plus/> Nova música</button></div>}/>
    <div className="music-health-row"><Card><Volume2/><strong>{project.music.filter(m=>!m.archived&&hasPlannerMusicAttachment(m)).length}</strong><span>faixas com áudio anexado</span></Card><Card><AlertTriangle/><strong>{villageValidation.filter(v=>!v.complete).length}</strong><span>vilas incompletas</span></Card><Card><button className="music-mute-card" onClick={()=>mutate(d=>{d.settings.muted=!d.settings.muted},false,'music:mute')}>{project.settings.muted?<VolumeX/>:<Volume2/>}<strong>{project.settings.muted?'Mudo ativado':'Som ativo'}</strong><span>O player continua avançando; apenas o áudio é silenciado.</span></button></Card></div>
    <div className="split-editor"><aside className="entity-list">{project.music.filter(m=>!m.archived).map(m=>{const ids=m.areaIds?.length?m.areaIds:m.areaId?[m.areaId]:[];return <button key={m.id} className={selectedId===m.id?'active':''} onClick={()=>setSelectedId(m.id)}><Music/><div><strong>{m.title}</strong><small>{m.role} · {m.jukeboxVisibility==='melodia'?`Melodia: ${m.melodyId||'ID em falta'}`:m.jukeboxVisibility==='base'?'Jukebox base':'fora do Jukebox'} · {ids.length} área(s) · {hasPlannerMusicAttachment(m)?'áudio anexado':'sem áudio anexado'}</small></div>{project.settings.persistentTrackId===m.id&&<Pin size={16}/>}</button>})}</aside>
      <section className="editor-pane">{!track?<EmptyState title="Selecione uma música" text="Anexe arquivos de áudio às fichas e relacione-os a áreas, mundos, bosses ou estados de vila."/>:<><div className="editor-heading"><input className="title-input" value={track.title} onChange={e=>update(m=>{m.title=e.target.value})}/><div className="editor-heading-actions"><button className="icon-button" disabled={!hasPlannerMusicAttachment(track)} title={hasPlannerMusicAttachment(track)?'Ouvir anexo':'Anexe um áudio para ouvir'} onClick={()=>setPreviewId(previewId===track.id?undefined:track.id)}>{previewId===track.id?<Pause/>:<Play/>}</button></div></div>
        <div className="form-grid two"><Field label="Função"><select value={track.role} onChange={e=>update(m=>{m.role=e.target.value as MusicTrack['role']})}><option value="area">Área</option><option value="vila_vazia">Vila Vazia</option><option value="vila_viva">Vila Viva/Restaurada</option><option value="vila_pos_boss">Vila Pós-boss</option><option value="boss_aproximacao">Boss aproximação</option><option value="boss_combate">Boss combate</option><option value="terra_gaia">Terra de Gaia</option><option value="apolo">Provação de Apolo</option><option value="global">Global</option></select></Field><Field label="Mundo principal"><select value={track.worldId??''} onChange={e=>update(m=>{m.worldId=e.target.value||undefined})}><option value="">Global</option>{project.worlds.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></Field></div><p className="muted">Repetir e Fixar ficam na barra musical superior, para controlarem a reprodução atual.</p><Card><SectionTitle>Jukebox</SectionTitle><div className="form-grid two"><Field label="Como aparece no Jukebox"><select value={track.jukeboxVisibility??'fora_jukebox'} onChange={e=>update(m=>{m.jukeboxVisibility=e.target.value as NonNullable<MusicTrack['jukeboxVisibility']>;if(m.jukeboxVisibility!=='melodia')m.melodyId=undefined})}><option value="base">Faixa base — sempre visível após comprar</option><option value="melodia">Melodia Selvagem — exige recolha</option><option value="fora_jukebox">Não listar no Jukebox</option></select></Field>{track.jukeboxVisibility==='melodia'&&<Field label="melodyId"><input value={track.melodyId??''} placeholder="ex.: melodia-trilho-musgo" onChange={e=>update(m=>{m.melodyId=e.target.value})}/></Field>}</div>{track.jukeboxVisibility==='melodia'&&!track.melodyId&&<p className="warning-callout">Sem melodyId, a faixa não pode ser filtrada individualmente por HasCollectedMelody.</p>}<p className="info-callout">Faixas base deixam melodyId vazio. Melodias só aparecem depois da recolha. Favoritos são guardados em GameVariables e não precisam de campo extra nesta ficha.</p></Card>
        <Card><SectionTitle>Áreas relacionadas</SectionTitle><p className="muted">Uma faixa pode ser reutilizada em várias áreas. Clique numa área para abrir a ficha.</p><div className="chips selectable music-area-choices">{project.areas.filter(a=>!track.worldId||a.worldId===track.worldId).map(a=><button key={a.id} className={relatedAreaIds.includes(a.id)?'selected':''} onClick={()=>toggleArea(a.id)}>{a.name}</button>)}</div>{relatedAreas.length>0&&<div className="relation-link-list">{relatedAreas.map(area=><Link key={area.id} to={`/area/${area.id}?tab=music`}><Link2/> {area.name}</Link>)}</div>}</Card>
        <div className={`media-health ${fileOk===false?'missing':fileOk?'ok':'empty'}`}>{fileOk===false?<><AlertTriangle/><div><strong>Anexo não encontrado</strong><span>{track.attachment?.originalName??track.filePath}</span><small>Use “Anexar novamente” para criar uma nova cópia gerenciada sem apagar a ficha.</small></div></>:fileOk?<><FileAudio/><div><strong>Áudio anexado ao Planejador</strong><span>{track.attachment?.originalName??'Arquivo de áudio gerenciado pelo projeto'}</span><small>Esta é a fonte que o player do Executor poderá reproduzir.</small></div></>:<><FileAudio/><div><strong>Nenhum áudio anexado</strong><span>A ficha e suas relações continuam válidas, mas não aparecerá no player do Executor.</span></div></>}</div>
        <div className="music-file-actions"><label className="secondary-button file-button"><Upload/> {hasPlannerMusicAttachment(track)?'Anexar novamente / substituir':'Anexar áudio ao Planejador'}<input type="file" accept="audio/*" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/></label>{hasPlannerMusicAttachment(track)&&<button className="text-button danger" onClick={()=>{if(confirm('Remover o áudio anexado desta ficha? A música e suas relações serão mantidas.'))update(m=>{m.filePath=undefined;m.dataUrl=undefined;m.attachment=undefined})}}><Trash2/> Remover áudio anexado</button>}</div>
        <Field label="Notas"><textarea value={track.notes} onChange={e=>update(m=>{m.notes=e.target.value})}/></Field>{previewId===track.id&&hasPlannerMusicAttachment(track)&&fileOk!==false&&<audio controls autoPlay src={mediaDisplayUrl(attachmentStorageValue(track))}/>}<EntityTools entityRef={{type:'music',id:track.id}} onArchived={()=>setSelectedId(undefined)}/></>}</section>
    </div>
    <Card className="village-music-validation"><SectionTitle>Validação das músicas de vila</SectionTitle><div className="validation-grid">{villageValidation.map(({world,found,complete})=><article key={world.id} className={complete?'complete':'incomplete'}><div><strong>{project.areas.find(a=>a.id===world.villageId)?.name}</strong><small>{world.name}</small></div>{(['Vazia','Viva/Restaurada','Pós-boss'] as const).map((label,index)=><button key={label} className={hasPlannerMusicAttachment(found[index])?'ok':'missing'} onClick={()=>{if(found[index])setSelectedId(found[index]!.id)}}>{label}: {found[index]?.title??'não cadastrada'}{found[index]&&!hasPlannerMusicAttachment(found[index])?' · sem anexo':''}</button>)}</article>)}</div></Card>
  </div>;
}
