import { useEffect, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { Card, EmptyState, Field, HelpTip, PageHeader, SectionTitle, StatusBadge, WarningDot } from '../components/Ui';
import { EntityTools } from '../components/EntityTools';
import { useProjectStore } from '../store/useProjectStore';
import type { EntityStatus, NpcActionKind, NpcActionPlan, NpcDef } from '../types';

export function NpcsPage() {
  const project=useProjectStore(s=>s.project); const mutate=useProjectStore(s=>s.mutate);
  const [params]=useSearchParams();
  const [selectedId,setSelectedId]=useState(project.npcs.find(n=>!n.archived)?.id);
  useEffect(()=>{const id=params.get('entity');if(id)setSelectedId(id)},[params]);
  const npc=project.npcs.find(n=>n.id===selectedId&&!n.archived);
  const update=(fn:(n:NpcDef)=>void)=>mutate(d=>{const target=d.npcs.find(x=>x.id===selectedId);if(target)fn(target)},false,`npc:${selectedId}`);
  const add=()=>{const world=project.worlds.find(w=>w.villageId);if(!world)return;const id=`npc-${Date.now()}`;mutate(d=>d.npcs.push({id,name:'Novo NPC',animal:'',worldId:world.id,villageAreaId:world.villageId!,rescueRequirement:'',rescueType:'interacao',villageLocation:'',preBossLine:'',postBossLine:'',hint:'',countsFor100:true,countsForVillageRestoration:true,populationRole:'resgatado',npcType:'comum',notes:'',missionIds:[],shopItems:[],status:'planejado',archived:false}),false,'npc:create');setSelectedId(id)};
  return <div><PageHeader title="NPCs" subtitle="Planeje resgate, vila, loja, missões e Actions de evento do backup 18/06 att." actions={<div className="inline-actions"><HelpTip topic="npc-actions"/><button className="primary-button" onClick={add}><Plus/> Novo NPC</button></div>}/>
    <div className="split-editor"><aside className="entity-list">{project.npcs.filter(n=>!n.archived).map(n=>{const missing=!n.rescueAreaId||!n.rescueRequirement;return <button key={n.id} className={selectedId===n.id?'active':''} onClick={()=>setSelectedId(n.id)}><div><strong>{n.name}</strong><small>{n.animal||'Animal não definido'} · {n.npcType}</small></div>{missing?<WarningDot title="Falta local ou condição de resgate"/>:<StatusBadge status={n.status}/>}</button>})}</aside>
      <section className="editor-pane">{!npc?<EmptyState title="Nenhum NPC selecionado" text="Crie um NPC e escolha a área onde ele será resgatado."/>:<>
        <div className="editor-heading"><input className="title-input" value={npc.name} onChange={e=>update(n=>{n.name=e.target.value})}/></div>
        <div className="form-grid three"><Field label="Animal"><input value={npc.animal} onChange={e=>update(n=>{n.animal=e.target.value})}/></Field><Field label="Tipo"><select value={npc.npcType} onChange={e=>update(n=>{n.npcType=e.target.value as NpcDef['npcType']})}><option value="comum">Comum</option><option value="comerciante">Comerciante</option><option value="contador">Contador de Histórias</option><option value="cartografo">Cartógrafo</option><option value="missao">NPC de missão</option><option value="outro">Outro</option></select></Field><Field label="Estado"><select value={npc.status} onChange={e=>update(n=>{n.status=e.target.value as EntityStatus})}><option value="planejado">Planejado</option><option value="unity">Configurado no Unity</option><option value="erro">Erro no Unity</option></select></Field></div>
        <div className="form-grid three"><Field label="Mundo e vila"><select value={npc.worldId} onChange={e=>update(n=>{const w=project.worlds.find(x=>x.id===e.target.value);n.worldId=e.target.value;n.villageAreaId=w?.villageId??''})}>{project.worlds.filter(w=>w.villageId).map(w=><option value={w.id} key={w.id}>{w.name} — {project.areas.find(a=>a.id===w.villageId)?.name}</option>)}</select></Field><Field label="Área onde é resgatado"><select value={npc.rescueAreaId??''} onChange={e=>update(n=>{n.rescueAreaId=e.target.value||undefined})}><option value="">Selecione…</option>{project.areas.filter(a=>a.worldId===npc.worldId&&a.type==='fase').map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="Tipo de resgate"><select value={npc.rescueType??'interacao'} onChange={e=>update(n=>{n.rescueType=e.target.value as NpcDef['rescueType']})}><option value="interacao">Interação simples</option><option value="presa_fisica">Presa física</option><option value="presa_ambiental">Presa ambiental</option><option value="assustada_fugitiva">Assustada/fugitiva</option></select></Field></div>
        <Field label="O que é necessário para resgatá-lo"><textarea value={npc.rescueRequirement} onChange={e=>update(n=>{n.rescueRequirement=e.target.value})}/></Field>
        <div className="form-grid three"><Field label="Onde fica na vila"><input value={npc.villageLocation??''} onChange={e=>update(n=>{n.villageLocation=e.target.value})}/></Field><Field label="Papel na população"><select value={npc.populationRole??'resgatado'} onChange={e=>update(n=>{n.populationRole=e.target.value as NpcDef['populationRole'];n.countsForVillageRestoration=e.target.value==='resgatado'})}><option value="resgatado">NPC resgatável obrigatório</option><option value="adicional">Habitante adicional / visitante</option><option value="nenhum">Não altera a população</option></select></Field><Field label="Conta para 100%"><select value={npc.countsFor100===false?'nao':'sim'} onChange={e=>update(n=>{n.countsFor100=e.target.value==='sim'})}><option value="sim">Sim</option><option value="nao">Não</option></select></Field></div>
        <div className="form-grid"><Field label="Fala antes do boss"><textarea value={npc.preBossLine??''} onChange={e=>update(n=>{n.preBossLine=e.target.value})}/></Field><Field label="Fala depois do boss"><textarea value={npc.postBossLine??''} onChange={e=>update(n=>{n.postBossLine=e.target.value})}/></Field></div>
        <Field label="Pista que dá"><textarea value={npc.hint??''} onChange={e=>update(n=>{n.hint=e.target.value})}/></Field>
        <Field label="Missões relacionadas"><div className="chips selectable">{project.missions.filter(m=>m.worldId===npc.worldId&&!m.archived).map(m=><button key={m.id} className={npc.missionIds.includes(m.id)?'selected':''} onClick={()=>update(n=>{n.missionIds=n.missionIds.includes(m.id)?n.missionIds.filter(x=>x!==m.id):[...n.missionIds,m.id]})}>{m.name}</button>)}</div></Field>
        {npc.npcType==='comerciante'&&<><SectionTitle>Loja</SectionTitle><div className="shop-list">{project.items.filter(i=>!i.archived).map(item=>{const row=npc.shopItems.find(x=>x.itemId===item.id);return <div key={item.id}><label><input type="checkbox" checked={!!row} onChange={()=>update(n=>{n.shopItems=row?n.shopItems.filter(x=>x.itemId!==item.id):[...n.shopItems,{itemId:item.id}]})}/>{item.name}</label>{row&&<input type="number" min="0" placeholder={`${item.defaultPrice}`} value={row.customPrice??''} onChange={e=>update(n=>{const r=n.shopItems.find(x=>x.itemId===item.id);if(r)r.customPrice=e.target.value===''?undefined:Number(e.target.value)})}/>}</div>})}</div></>}
        <NpcActionsEditor npc={npc} update={update} animals={project.animals.map(a=>({id:a.id,name:a.name}))}/>
        <Field label="Notas"><textarea value={npc.notes} onChange={e=>update(n=>{n.notes=e.target.value})}/></Field>
        <EntityTools entityRef={{type:'npc',id:npc.id}} onArchived={()=>setSelectedId(undefined)}/>
      </>}</section></div>
  </div>;
}

const ACTION_LABELS:Record<NpcActionKind,string>={
  mostrar_sementes:'Mostrar Sementes',alterar_sementes:'Pagar ou ganhar Sementes',
  guardar_status:'Guardar status do jogador',restaurar_status:'Restaurar status guardado',descartar_status:'Descartar snapshot',
  bloquear_animais:'Bloquear animais temporariamente',desbloquear_animais:'Restaurar/desbloquear animais',
  resgatar_npc:'Registar resgate de NPC',adicionar_populacao_vila:'Adicionar habitante à vila',definir_populacao_vila:'Definir população da vila',sincronizar_populacao_vila:'Sincronizar resgates da vila',
  tutorial:'Mostrar mensagem de tutorial',variavel:'Alterar variável',outro:'Outra Action'
};
const SNAPSHOT_FIELDS=[
  ['seeds','Sementes'],['runes','Runas de Gaia disponíveis'],['ecos','Ecos Perdidos'],['brotos','Brotos em stock'],
  ['currentHearts','Corações actuais'],['maxHearts','Máximo de corações'],['inventory','Inventário completo'],
  ['equippedItem','Item equipado'],['freedAnimals','Animais libertados'],['lockedForms','Bloqueios temporários de formas'],
] as const;
function NpcActionsEditor({npc,update,animals}:{npc:NpcDef;update:(fn:(n:NpcDef)=>void)=>void;animals:Array<{id:string;name:string}>}){
  const project=useProjectStore(s=>s.project);
  const addAction=()=>update(n=>{n.eventActions??=[];n.eventActions.push({id:`npc-action-${crypto.randomUUID()}`,kind:'mostrar_sementes',label:'Mostrar Sementes',showHud:true,animateHud:true,fields:[],animalIds:[],countsForVillageRestoration:true,implementationStatus:'implementado',notes:''})});
  const patch=(id:string,data:Partial<NpcActionPlan>)=>update(n=>{const action=n.eventActions?.find(a=>a.id===id);if(action)Object.assign(action,data)});
  const remove=(id:string)=>update(n=>{n.eventActions=(n.eventActions??[]).filter(a=>a.id!==id)});
  const toggle=(values:string[]|undefined,id:string)=>values?.includes(id)?values.filter(x=>x!==id):[...(values??[]),id];
  return <Card className="npc-actions-card"><SectionTitle action={<div className="inline-actions"><HelpTip topic="npc-actions"/><button className="text-button" onClick={addAction}><Plus/> Adicionar Action</button></div>}>Actions de evento</SectionTitle><p className="muted">O backup 18/06 att permite resgates idempotentes, população adicional, snapshots persistentes, bloqueio de formas e tutoriais. Use IDs estáveis e configure o autosave depois de progressos importantes.</p>{(npc.eventActions??[]).length===0?<p className="empty-inline">Nenhuma Action planeada.</p>:<div className="npc-action-list">{(npc.eventActions??[]).map(action=><div className="npc-action-row" key={action.id}><div className="npc-action-heading"><input value={action.label} onChange={e=>patch(action.id,{label:e.target.value})}/><select value={action.kind} onChange={e=>patch(action.id,{kind:e.target.value as NpcActionKind,label:ACTION_LABELS[e.target.value as NpcActionKind],implementationStatus:'implementado'})}>{Object.entries(ACTION_LABELS).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select><button className="icon-button danger" onClick={()=>remove(action.id)}><Trash2/></button></div>
        {action.kind==='alterar_sementes'&&<div className="form-grid three"><Field label="Quantidade"><input type="number" value={action.amount??0} onChange={e=>patch(action.id,{amount:Number(e.target.value)})}/></Field><Field label="Mostrar na HUD"><select value={action.showHud===false?'nao':'sim'} onChange={e=>patch(action.id,{showHud:e.target.value==='sim'})}><option value="sim">Sim</option><option value="nao">Não, alteração silenciosa</option></select></Field><Field label="Animar contador"><select value={action.animateHud===false?'nao':'sim'} onChange={e=>patch(action.id,{animateHud:e.target.value==='sim'})}><option value="sim">Sim, até 1 segundo</option><option value="nao">Trocar imediatamente</option></select></Field></div>}
        {action.kind==='mostrar_sementes'&&<p className="info-callout">Mostra o saldo actual de Sementes durante o diálogo, sem alterar o valor.</p>}
        {(action.kind==='guardar_status'||action.kind==='restaurar_status'||action.kind==='descartar_status')&&<><Field label="Chave do snapshot"><input value={action.snapshotKey??''} placeholder="ex.: antes_do_roubo" onChange={e=>patch(action.id,{snapshotKey:e.target.value})}/></Field>{action.kind==='guardar_status'&&<Field label="O que guardar"><div className="chips selectable">{SNAPSHOT_FIELDS.map(([id,label])=><button key={id} className={(action.fields??[]).includes(id)?'selected':''} onClick={()=>patch(action.id,{fields:toggle(action.fields,id)})}>{label}</button>)}</div></Field>}{action.kind==='restaurar_status'&&<label className="check-row"><input type="checkbox" checked={action.discardAfterRestore??false} onChange={e=>patch(action.id,{discardAfterRestore:e.target.checked})}/> Descartar o snapshot depois de restaurar</label>}<p className="info-callout">Snapshots activos entram no SaveData e sobrevivem a mudança de cena ou carregamento do jogo.</p></>}
        {(action.kind==='bloquear_animais'||action.kind==='desbloquear_animais')&&<Field label={action.kind==='bloquear_animais'?'Animais que ficam cinzentos e indisponíveis':'Animais a restaurar'}><div className="chips selectable">{animals.map(animal=><button key={animal.id} disabled={animal.id==='iris-base'} className={(action.animalIds??[]).includes(animal.id)?'selected':''} onClick={()=>patch(action.id,{animalIds:toggle(action.animalIds,animal.id)})}>{animal.name}{animal.id==='iris-base'?' · protegida':''}</button>)}</div></Field>}
        {action.kind==='resgatar_npc'&&<><div className="form-grid"><Field label="npcId único"><input value={action.npcId??npc.id} onChange={e=>patch(action.id,{npcId:e.target.value})}/></Field><Field label="Área do resgate"><select value={action.areaId??npc.rescueAreaId??''} onChange={e=>patch(action.id,{areaId:e.target.value})}><option value="">Seleccione…</option>{project.areas.filter(a=>a.type==='fase').map(a=><option value={a.id} key={a.id}>{project.worlds.find(w=>w.id===a.worldId)?.name} — {a.name}</option>)}</select></Field></div><label className="check-row"><input type="checkbox" checked={action.countsForVillageRestoration!==false} onChange={e=>patch(action.id,{countsForVillageRestoration:e.target.checked})}/> Conta para a restauração e para rescuedCount</label><p className="info-callout">Com npcId preenchido, repetir o evento não duplica a contagem e a variável NpcResgatado_&lt;npcId&gt; é criada automaticamente.</p></>}
        {action.kind==='adicionar_populacao_vila'&&<><Field label="Vila"><select value={action.villageId??npc.villageAreaId} onChange={e=>patch(action.id,{villageId:e.target.value})}>{project.areas.filter(a=>a.type==='vila').map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><p className="info-callout">Use para lojistas, visitantes ou NPCs de evento. Soma additionalPopulation sem alterar rescuedCount nem os 100%.</p></>}
        {action.kind==='definir_populacao_vila'&&<div className="form-grid three"><Field label="Vila"><select value={action.villageId??npc.villageAreaId} onChange={e=>patch(action.id,{villageId:e.target.value})}>{project.areas.filter(a=>a.type==='vila').map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="População actual"><input type="number" min="0" value={action.currentPopulation??0} onChange={e=>patch(action.id,{currentPopulation:Number(e.target.value)})}/></Field><Field label="Máximo"><input type="number" min="0" value={action.maxPopulation??0} onChange={e=>patch(action.id,{maxPopulation:Number(e.target.value)})}/></Field></div>}
        {action.kind==='sincronizar_populacao_vila'&&<><Field label="Mundo"><select value={action.worldId??npc.worldId} onChange={e=>patch(action.id,{worldId:e.target.value})}>{project.worlds.filter(w=>w.villageId).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></Field><p className="info-callout">Recalcula rescuedCount pelas áreas do mundo e preserva additionalPopulation. Útil após migração de save antigo ou alteração em lote.</p></>}
        {action.kind==='tutorial'&&<p className="info-callout">Seleccione ou descreva uma mensagem criada em Sistemas → Tutoriais. Prioridades importante, média e popup são suportadas.</p>}
        <Field label="Notas / parâmetros"><textarea value={action.notes??''} onChange={e=>patch(action.id,{notes:e.target.value})}/></Field><small className="implementation-state ready">Disponível no backup 18/06 att</small></div>)}</div>}</Card>;
}
