import { useMemo, useState } from 'react';
import { BookOpen, CheckCircle2, ClipboardCheck, Code2, Lightbulb, PlayCircle, TriangleAlert } from 'lucide-react';
import { Card, Field, PageHeader, SectionTitle } from '../components/Ui';
import { schoolModules } from '../data/school';
import { useProjectStore } from '../store/useProjectStore';

export function SchoolPage(){
  const project=useProjectStore(s=>s.project);const mutate=useProjectStore(s=>s.mutate);const [selected,setSelected]=useState(0);const [areaId,setAreaId]=useState(project.areas.find(a=>a.type==='fase')?.id??'');
  const module=schoolModules[selected];
  const progress=project.schoolProgress[module.id]??{completed:false,notes:'',appliedAreaIds:[]};
  const completedCount=useMemo(()=>schoolModules.filter(m=>project.schoolProgress[m.id]?.completed).length,[project.schoolProgress]);
  const patchProgress=(patch:Partial<typeof progress>)=>mutate(d=>{const current=d.schoolProgress[module.id]??{completed:false,notes:'',appliedAreaIds:[]};d.schoolProgress[module.id]={...current,...patch}},false,`school:${module.id}`);
  const apply=()=>{if(!areaId)return;mutate(d=>{const area=d.areas.find(a=>a.id===areaId);if(!area)return;area.notes=[area.notes,module.applyTemplate,`Exercício: ${module.exercise}`,`Checklist: ${module.checklist.join(' | ')}`].filter(Boolean).join('\n');const current=d.schoolProgress[module.id]??{completed:false,notes:'',appliedAreaIds:[]};if(!current.appliedAreaIds.includes(areaId))current.appliedAreaIds.push(areaId);d.schoolProgress[module.id]=current;d.areaResources.push({id:`nota-escola-${module.id}-${crypto.randomUUID().slice(0,8)}`,areaId,kind:'levelNote',name:`Escola ${module.id} — ${module.title}`,description:module.applyTemplate,status:'planejado',notes:`Exercício: ${module.exercise}\nChecklist: ${module.checklist.join('\n- ')}`,archived:false})},true,`school:apply:${module.id}:${areaId}`);alert('O módulo foi aplicado às notas e aos recursos de level design da área.')};

  return <div><PageHeader title="Escola de Level Design" subtitle={`Curso personalizado para Animals. ${completedCount}/${schoolModules.length} módulos concluídos.`}/><div className="school-progress"><div style={{width:`${completedCount/schoolModules.length*100}%`}}/><span>{Math.round(completedCount/schoolModules.length*100)}%</span></div><div className="school-layout"><aside className="school-nav">{schoolModules.map((item,i)=>{const done=project.schoolProgress[item.id]?.completed;return <button className={selected===i?'active':''} key={item.id} onClick={()=>setSelected(i)}><span>{done?<CheckCircle2/>:item.id}</span><strong>{item.title}</strong></button>})}</aside><article className="school-content"><div className="school-hero"><BookOpen/><span>Módulo {module.id}</span><h1>{module.title}</h1><p>{module.principle}</p></div>
      <Card><SectionTitle>Explicação completa</SectionTitle><div className="school-long-text">{module.explanation.map(text=><p key={text}>{text}</p>)}</div></Card>
      <div className="two-column"><Card><SectionTitle action={<Lightbulb/>}>Exemplos em Animals</SectionTitle>{module.examples.map(example=><div className="school-example" key={example.title}><strong>{example.title}</strong><p>{example.text}</p></div>)}</Card><Card className="school-errors"><SectionTitle action={<TriangleAlert/>}>Erros comuns</SectionTitle><ul>{module.mistakes.map(item=><li key={item}>{item}</li>)}</ul></Card></div>
      <Card><SectionTitle action={<PlayCircle/>}>Exercício</SectionTitle><p className="school-exercise">{module.exercise}</p></Card>
      <div className="two-column"><Card><SectionTitle action={<ClipboardCheck/>}>Checklist específico</SectionTitle><div className="school-checklist">{module.checklist.map(item=><label key={item}><input type="checkbox"/><span>{item}</span></label>)}</div></Card><Card><SectionTitle action={<Code2/>}>Scripts e ferramentas relacionados</SectionTitle><div className="chips">{module.scripts.map(item=><span key={item}>{item}</span>)}</div></Card></div>
      <Card><SectionTitle>Aplicar na área atual</SectionTitle><p className="muted">Cria uma Nota de Level Design e acrescenta o exercício e o checklist às notas da área.</p><div className="school-apply-row"><Field label="Área"><select value={areaId} onChange={e=>setAreaId(e.target.value)}>{project.areas.filter(a=>a.type==='fase'||a.type==='hub'||a.type==='boss').map(area=><option value={area.id} key={area.id}>{project.worlds.find(w=>w.id===area.worldId)?.name} — {area.name}</option>)}</select></Field><button className="primary-button" onClick={apply}>Aplicar na área</button></div>{progress.appliedAreaIds.length>0&&<div className="chips">{progress.appliedAreaIds.map(id=><span key={id}>{project.areas.find(a=>a.id===id)?.name??id}</span>)}</div>}</Card>
      <Card><SectionTitle>Notas pessoais</SectionTitle><Field label="O que aprendi ou preciso testar"><textarea value={progress.notes} onChange={e=>patchProgress({notes:e.target.value})}/></Field><label className="school-complete-toggle"><input type="checkbox" checked={progress.completed} onChange={e=>patchProgress({completed:e.target.checked})}/><span><CheckCircle2/> Marcar módulo como concluído</span></label></Card>
    </article></div></div>;
}
