import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { Stage, Layer, Rect, Text, Group, Line, Arrow, Circle, Transformer, Image as KonvaImage } from 'react-konva';
import useImage from 'use-image';
import type Konva from 'konva';
import { Activity, Download, Eraser, Focus, Fullscreen, Hand, ImagePlus, Layers3, Lock, MousePointer2, Paintbrush, RotateCcw, Search, Trash2, Unlock, ZoomIn, ZoomOut } from 'lucide-react';
import { useUiStore } from '../store/useUiStore';
import { HelpTip, PageHeader } from '../components/Ui';
import { mediaDisplayUrl, persistMediaFile } from '../lib/storage';
import { useProjectStore } from '../store/useProjectStore';
import { originalWorldMapPlan } from '../data/seed';
import type { GaiaMapBackgroundImage, GaiaMapDrawing, GaiaMapEdge, GaiaMapNode } from '../types';

type Tool='select'|'hand'|'draw'|'erase';
type LayerKey='nodes'|'edges'|'images'|'drawings'|'grid';
const NODE_W=190,NODE_H=78;

export function WorldMapPage(){
  const project=useProjectStore(s=>s.project),mutate=useProjectStore(s=>s.mutate),undo=useProjectStore(s=>s.undo),redo=useProjectStore(s=>s.redo);
  const plan=project.worldMap;
  const rootRef=useRef<HTMLDivElement|null>(null),canvasRef=useRef<HTMLDivElement|null>(null),stageRef=useRef<Konva.Stage|null>(null),trRef=useRef<Konva.Transformer|null>(null);
  const [size,setSize]=useState({w:900,h:680}),[tool,setTool]=useState<Tool>('select'),[selected,setSelected]=useState<string>(),[search,setSearch]=useState(''),[drawing,setDrawing]=useState<number[]>([]),[drawColor,setDrawColor]=useState('#d6b15b'),[fullscreen,setFullscreen]=useState(false),[layers,setLayers]=useState<Record<LayerKey,{visible:boolean;locked:boolean}>>({nodes:{visible:true,locked:false},edges:{visible:true,locked:false},images:{visible:true,locked:false},drawings:{visible:true,locked:false},grid:{visible:true,locked:false}}),[linking,setLinking]=useState<{source:string;x:number;y:number;endX:number;endY:number}>(),[exportOpen,setExportOpen]=useState(false);
  const safeNodes=useMemo(()=>plan.nodes.filter(node=>node&&node.id&&node.areaId&&Number.isFinite(node.x)&&Number.isFinite(node.y)),[plan.nodes]);
  const safeNodeIds=useMemo(()=>new Set(safeNodes.map(node=>node.id)),[safeNodes]);
  const safeEdges=useMemo(()=>plan.edges.filter(edge=>edge&&edge.id&&edge.source!==edge.target&&safeNodeIds.has(edge.source)&&safeNodeIds.has(edge.target)),[plan.edges,safeNodeIds]);
  const selectedBg=plan.backgroundImages.find(bg=>`bg:${bg.id}`===selected),selectedEdge=plan.edges.find(e=>`edge:${e.id}`===selected),selectedNode=plan.nodes.find(n=>`node:${n.id}`===selected);
  const placed=useMemo(()=>new Set(safeNodes.map(n=>n.areaId)),[safeNodes]);
  const available=useMemo(()=>project.worlds.map(world=>({world,areas:project.areas.filter(a=>a.worldId===world.id&&!placed.has(a.id)&&a.name.toLowerCase().includes(search.toLowerCase()))})).filter(g=>g.areas.length),[project.worlds,project.areas,placed,search]);
  useEffect(()=>{if(!canvasRef.current)return;const ob=new ResizeObserver(([e])=>setSize({w:Math.max(600,e.contentRect.width),h:Math.max(500,e.contentRect.height)}));ob.observe(canvasRef.current);return()=>ob.disconnect()},[]);
  useEffect(()=>{const shape=stageRef.current?.findOne(`#${cssId(selectedBg?.id??'')}`);if(shape&&selectedBg&&trRef.current){trRef.current.nodes([shape]);trRef.current.getLayer()?.batchDraw()}else trRef.current?.nodes([])},[selectedBg,selected]);
  useEffect(()=>{const h=()=>setFullscreen(document.fullscreenElement===rootRef.current);document.addEventListener('fullscreenchange',h);return()=>document.removeEventListener('fullscreenchange',h)},[]);
  const setImmersive=useUiStore(s=>s.setImmersive);
  useEffect(()=>{setImmersive(fullscreen);return()=>setImmersive(false)},[fullscreen,setImmersive]);
  const worldPointer=useCallback(()=>{const st=stageRef.current,p=st?.getPointerPosition();if(!st||!p)return{x:0,y:0};return{x:(p.x-st.x())/st.scaleX(),y:(p.y-st.y())/st.scaleY()}},[]);
  const snap=(v:number)=>plan.snapToGrid?Math.round(v/plan.gridSize)*plan.gridSize:v;
  const addNodeAt=(areaId:string,x:number,y:number)=>{const area=project.areas.find(a=>a.id===areaId);if(!area||placed.has(areaId))return;const node:GaiaMapNode={id:`gaia-${crypto.randomUUID()}`,areaId,x:snap(x-NODE_W/2),y:snap(y-NODE_H/2),unlockMode:area.unlockMode,unlockMissionId:area.unlockMissionId,notes:'',worldIntro:false};mutate(d=>d.worldMap.nodes.push(node),false,'gaia:add-node');setSelected(`node:${node.id}`)};
  const dropArea=(e:React.DragEvent)=>{e.preventDefault();const areaId=e.dataTransfer.getData('application/animals-area');if(!areaId)return;const rect=canvasRef.current!.getBoundingClientRect(),st=stageRef.current!;const px=e.clientX-rect.left,py=e.clientY-rect.top;addNodeAt(areaId,(px-st.x())/st.scaleX(),(py-st.y())/st.scaleY())};
  const startLink=(node:GaiaMapNode,x:number,y:number,e:Konva.KonvaEventObject<MouseEvent|TouchEvent>)=>{if(layers.edges.locked)return;e.cancelBubble=true;setLinking({source:node.id,x,y,endX:x,endY:y});setSelected(undefined)};
  const finishLink=(target?:GaiaMapNode)=>{if(!linking||!target||linking.source===target.id){setLinking(undefined);return;}const exists=safeEdges.some(e=>(e.source===linking.source&&e.target===target.id)||(e.source===target.id&&e.target===linking.source));if(!exists)mutate(d=>{d.worldMap.edges.push({id:crypto.randomUUID(),source:linking.source,target:target.id,label:'',kind:'principal',bidirectional:false,notes:'',controlPoints:[]});},false,'gaia:add-edge');setLinking(undefined)};
  const nodeAtPointer=()=>{const p=worldPointer();return [...safeNodes].reverse().find(node=>p.x>=node.x&&p.x<=node.x+NODE_W&&p.y>=node.y&&p.y<=node.y+NODE_H)};
  const resetOriginalMap=()=>{if(!confirm('Resetar nós e ligações para o mapa original? Imagens e desenhos serão preservados.'))return;mutate(d=>{d.worldMap.nodes=structuredClone(originalWorldMapPlan.nodes);d.worldMap.edges=structuredClone(originalWorldMapPlan.edges);d.worldMap.gridSize=originalWorldMapPlan.gridSize;d.worldMap.snapToGrid=originalWorldMapPlan.snapToGrid;},true,'gaia:reset-original');setSelected(undefined);setLinking(undefined);window.setTimeout(fit,50)};
  const deleteSelected=()=>{if(!selected)return;mutate(d=>{if(selected.startsWith('node:')){const id=selected.slice(5);d.worldMap.nodes=d.worldMap.nodes.filter(n=>n.id!==id);d.worldMap.edges=d.worldMap.edges.filter(e=>e.source!==id&&e.target!==id)}else if(selected.startsWith('edge:'))d.worldMap.edges=d.worldMap.edges.filter(e=>e.id!==selected.slice(5));else if(selected.startsWith('bg:'))d.worldMap.backgroundImages=d.worldMap.backgroundImages.filter(b=>b.id!==selected.slice(3))},false,'gaia:delete');setSelected(undefined)};
  const addBackground=async(file:File)=>{const path=await persistMediaFile(file,'terra-de-gaia/backgrounds');const center=screenCenter(stageRef.current,size);const bg:GaiaMapBackgroundImage={id:crypto.randomUUID(),filePath:path,x:center.x-300,y:center.y-200,width:600,height:400,opacity:.72,rotation:0,locked:false,name:file.name};mutate(d=>d.worldMap.backgroundImages.push(bg),false,'gaia:add-bg');setSelected(`bg:${bg.id}`)};
  const fit=()=>{const b=bounds(plan);const st=stageRef.current;if(!st)return;if(!b){st.position({x:size.w/2,y:size.h/2});st.scale({x:1,y:1});return}const s=Math.max(.12,Math.min(1.7,Math.min((size.w-160)/b.width,(size.h-160)/b.height)));st.scale({x:s,y:s});st.position({x:size.w/2-(b.x+b.width/2)*s,y:size.h/2-(b.y+b.height/2)*s});st.batchDraw()};
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches('input,textarea,select'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();if(e.shiftKey)redo();else undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}if(e.key==='Delete')deleteSelected();if(e.key==='Escape'){setLinking(undefined);setDrawing([]);setTool('select')}if(e.key.toLowerCase()==='f')fit()};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)});
  const exportPng=()=>{const st=stageRef.current,b=bounds(plan);if(!st||!b)return alert('Coloque pelo menos um elemento no mapa.');const url=st.toDataURL({x:b.x-50,y:b.y-50,width:b.width+100,height:b.height+100,pixelRatio:2});const a=document.createElement('a');a.href=url;a.download='animals-terra-de-gaia.png';a.click();setExportOpen(false)};
  const onStageDown=(e:Konva.KonvaEventObject<MouseEvent|TouchEvent>)=>{if(e.target!==e.target.getStage())return;if(tool==='select')setSelected(undefined);if(tool==='draw'){const p=worldPointer();setDrawing([p.x,p.y])}if(tool==='erase'){const p=worldPointer(),hit=nearDrawing(plan.drawings,p.x,p.y,20/(stageRef.current?.scaleX()||1));if(hit)mutate(d=>{d.worldMap.drawings=d.worldMap.drawings.filter(x=>x.id!==hit.id)},false,'gaia:erase')}};
  const onStageMove=()=>{const p=worldPointer();if(linking)setLinking(l=>l?{...l,endX:p.x,endY:p.y}:l);if(tool==='draw'&&drawing.length)setDrawing(v=>[...v,p.x,p.y])};
  const onStageUp=()=>{if(tool==='draw'&&drawing.length>3){const line:GaiaMapDrawing={id:crypto.randomUUID(),points:drawing,color:drawColor,width:6};mutate(d=>d.worldMap.drawings.push(line),false,'gaia:draw')}setDrawing([]);if(linking)finishLink(nodeAtPointer())};
  return <div className={`gaia-page-v2 ${fullscreen?'is-fullscreen':''}`} ref={rootRef}>
    {!fullscreen&&<PageHeader title="Terra de Gaia" subtitle="Arraste as áreas da biblioteca para o mapa e puxe os conectores para criar ligações." actions={<div className="inline-actions"><HelpTip topic="terra-gaia"/><Link className="secondary-button" to="/world-map/analysis"><Activity/> Analisar mapa</Link></div>}/>}
    <div className="gaia-toolbar"><button className={tool==='select'?'active':''} onClick={()=>setTool('select')}><MousePointer2/> Selecionar</button><button className={tool==='hand'?'active':''} onClick={()=>setTool('hand')}><Hand/> Mão</button><button className={tool==='draw'?'active':''} onClick={()=>setTool('draw')}><Paintbrush/> Desenhar</button><input type="color" value={drawColor} onChange={e=>setDrawColor(e.target.value)}/><button className={tool==='erase'?'active':''} onClick={()=>setTool('erase')}><Eraser/> Apagar desenho</button><label className="tool-upload"><input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)void addBackground(f)}}/><ImagePlus/> Imagem</label><button onClick={fit}><Focus/> Centralizar</button><button onClick={resetOriginalMap} title="Restaura a topologia original sem apagar imagens ou desenhos"><RotateCcw/> Resetar mapa original</button><button onClick={()=>{const st=stageRef.current;if(st){st.scale({x:st.scaleX()*1.15,y:st.scaleY()*1.15});st.batchDraw()}}}><ZoomIn/></button><button onClick={()=>{const st=stageRef.current;if(st){st.scale({x:st.scaleX()/1.15,y:st.scaleY()/1.15});st.batchDraw()}}}><ZoomOut/></button><button onClick={()=>void(rootRef.current?.requestFullscreen())}><Fullscreen/> Tela cheia</button><button onClick={()=>setExportOpen(true)}><Download/> Exportar</button></div>
    <div className="gaia-workspace">
      <aside className="gaia-area-library gaia-library-left"><h3>Áreas disponíveis</h3><div className="library-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Filtrar áreas"/></div><p className="muted">Somente áreas ainda não colocadas aparecem aqui.</p>{available.map(group=><section key={group.world.id}><h4 style={{borderColor:group.world.theme.primary}}>{group.world.name}<span>{group.areas.length}</span></h4>{group.areas.map(area=><div draggable className="draggable-area" key={area.id} onDragStart={e=>{e.dataTransfer.setData('application/animals-area',area.id);e.dataTransfer.effectAllowed='copy'}} onDoubleClick={()=>{const c=screenCenter(stageRef.current,size);addNodeAt(area.id,c.x,c.y)}}><span className="world-dot" style={{background:group.world.theme.primary}}/><div><strong>{area.name}</strong><small>{area.type} · {area.unlockMode==='runes'?`${area.accessCost} Runas`:area.unlockMode}</small></div></div>)}</section>)}{available.length===0&&<div className="empty-state">Todas as áreas filtradas já estão no mapa.</div>}</aside>
      <div className="gaia-canvas" ref={canvasRef} onDragOver={e=>e.preventDefault()} onDrop={dropArea}>
        <Stage ref={stageRef} width={size.w} height={size.h} draggable={tool==='hand'} onWheel={e=>{e.evt.preventDefault();const st=stageRef.current;if(!st)return;const old=st.scaleX(),pt=st.getPointerPosition()!,mouse={x:(pt.x-st.x())/old,y:(pt.y-st.y())/old},next=Math.max(.12,Math.min(4,e.evt.deltaY<0?old*1.1:old/1.1));st.scale({x:next,y:next});st.position({x:pt.x-mouse.x*next,y:pt.y-mouse.y*next})}} onMouseDown={onStageDown} onMouseMove={onStageMove} onMouseUp={onStageUp}>
          <Layer visible={layers.grid.visible}>{layers.grid.visible&&<Grid grid={plan.gridSize}/>}</Layer>
          <Layer visible={layers.images.visible}>{plan.backgroundImages.map(bg=><BgShape key={bg.id} bg={bg} selected={selected===`bg:${bg.id}`} locked={layers.images.locked||bg.locked} onSelect={()=>setSelected(`bg:${bg.id}`)} onChange={p=>mutate(d=>{const b=d.worldMap.backgroundImages.find(x=>x.id===bg.id);if(b)Object.assign(b,p)},false,`gaia:bg:${bg.id}`)}/>)}<Transformer ref={trRef}/></Layer>
          <Layer visible={layers.drawings.visible}>{plan.drawings.map(line=><Line key={line.id} points={line.points} stroke={line.color} strokeWidth={line.width} lineCap="round" lineJoin="round" listening={false}/>) }{drawing.length>1&&<Line points={drawing} stroke={drawColor} strokeWidth={6} lineCap="round"/>}</Layer>
          <Layer visible={layers.edges.visible}>{safeEdges.map(edge=><Edge key={edge.id} edge={edge} nodes={safeNodes} selected={selected===`edge:${edge.id}`} locked={layers.edges.locked} onSelect={()=>setSelected(`edge:${edge.id}`)} onDelete={()=>{mutate(d=>{d.worldMap.edges=d.worldMap.edges.filter(value=>value.id!==edge.id)},false,`gaia:delete-edge:${edge.id}`);setSelected(undefined)}} onControl={(x,y)=>mutate(d=>{const e=d.worldMap.edges.find(v=>v.id===edge.id);if(e)e.controlPoints=[x,y]},false,`gaia:edge-control:${edge.id}`)}/>)}{linking&&<Line points={[linking.x,linking.y,linking.endX,linking.endY]} stroke="#ffe38b" strokeWidth={3} dash={[8,6]}/>}</Layer>
          <Layer visible={layers.nodes.visible}>{safeNodes.map(node=><Node key={node.id} node={node} project={project} selected={selected===`node:${node.id}`} locked={layers.nodes.locked} onSelect={()=>setSelected(`node:${node.id}`)} onMove={(x,y)=>mutate(d=>{const n=d.worldMap.nodes.find(v=>v.id===node.id);if(n){n.x=snap(x);n.y=snap(y)}},false,`gaia:move:${node.id}`)} onStartLink={(x,y,e)=>startLink(node,x,y,e)}/>)}</Layer>
        </Stage><div className="gaia-hint">Arraste uma área da esquerda. Para ligar, puxe um ponto amarelo de um nó até outro. Selecione a linha e pressione Delete, ou clique nela com o botão direito.</div>
      </div>
      <aside className="gaia-left-panel gaia-layers-right"><h3><Layers3/> Camadas</h3>{(Object.keys(layers) as LayerKey[]).map(k=><div className="layer-row" key={k}><label><input type="checkbox" checked={layers[k].visible} onChange={e=>setLayers(v=>({...v,[k]:{...v[k],visible:e.target.checked}}))}/>{layerName(k)}</label><button className="icon-button" onClick={()=>setLayers(v=>({...v,[k]:{...v[k],locked:!v[k].locked}}))}>{layers[k].locked?<Lock/>:<Unlock/>}</button></div>)}<label>Grelha<input type="number" min="8" value={plan.gridSize} onChange={e=>mutate(d=>{d.worldMap.gridSize=Number(e.target.value)},false,'gaia:grid')}/></label><label className="check-row"><input type="checkbox" checked={plan.snapToGrid} onChange={e=>mutate(d=>{d.worldMap.snapToGrid=e.target.checked},false,'gaia:snap')}/> Encaixar na grelha</label>{selectedNode&&<NodeInspector node={selectedNode} project={project} onChange={p=>mutate(d=>{const n=d.worldMap.nodes.find(x=>x.id===selectedNode.id);if(n)Object.assign(n,p)},false,`gaia:node:${selectedNode.id}`)}/>} {selectedEdge&&<EdgeInspector edge={selectedEdge} onChange={p=>mutate(d=>{const edge=d.worldMap.edges.find(x=>x.id===selectedEdge.id);if(edge)Object.assign(edge,p)},false,`gaia:edge:${selectedEdge.id}`)}/>} {selectedBg&&<BgInspector bg={selectedBg} onChange={p=>mutate(d=>{const bg=d.worldMap.backgroundImages.find(x=>x.id===selectedBg.id);if(bg)Object.assign(bg,p)},false,`gaia:bg:${selectedBg.id}`)}/>} {selected&&<button className="danger-button" onClick={deleteSelected}><Trash2/> Remover selecionado</button>}</aside>
    </div>
    {exportOpen&&<div className="modal-backdrop"><div className="modal-card"><h2>Exportar Terra de Gaia</h2><p>A exportação usa os limites reais dos elementos colocados.</p><div className="modal-actions"><button className="secondary-button" onClick={()=>setExportOpen(false)}>Cancelar</button><button className="primary-button" onClick={exportPng}><Download/> Exportar PNG</button></div></div></div>}
  </div>;
}
function Node({node,project,selected,locked,onSelect,onMove,onStartLink}:{node:GaiaMapNode;project:ReturnType<typeof useProjectStore.getState>['project'];selected:boolean;locked:boolean;onSelect:()=>void;onMove:(x:number,y:number)=>void;onStartLink:(x:number,y:number,e:Konva.KonvaEventObject<MouseEvent|TouchEvent>)=>void}){const area=project.areas.find(a=>a.id===node.areaId),world=project.worlds.find(w=>w.id===area?.worldId);const handles=[[0,NODE_H/2],[NODE_W,NODE_H/2],[NODE_W/2,0],[NODE_W/2,NODE_H]];return <Group x={node.x} y={node.y} draggable={!locked} onClick={e=>{e.cancelBubble=true;onSelect()}} onDragEnd={e=>onMove(e.target.x(),e.target.y())}><Rect width={NODE_W} height={NODE_H} cornerRadius={12} fill="#172129" stroke={selected?'#fff':world?.theme.primary??'#6ba'} strokeWidth={selected?4:2}/><Rect width={7} height={NODE_H} cornerRadius={[12,0,0,12]} fill={world?.theme.primary}/><Text x={18} y={13} width={NODE_W-30} text={area?.name??'Área ausente'} fill="#fff" fontSize={15} fontStyle="bold" ellipsis wrap="none"/><Text x={18} y={38} width={NODE_W-30} text={`${area?.type} · ${unlockText(area)}`} fill="#9dabb4" fontSize={11}/><Text x={18} y={56} width={NODE_W-30} text={`${area?.runeTarget??0} Runas planejadas`} fill="#d2dade" fontSize={11}/>{handles.map(([x,y],i)=><Circle key={i} x={x} y={y} radius={7} fill="#ffe38b" stroke="#2d2410" strokeWidth={2} onMouseDown={e=>onStartLink(node.x+x,node.y+y,e)} onTouchStart={e=>onStartLink(node.x+x,node.y+y,e)}/>)}</Group>}
function Edge({edge,nodes,selected,locked,onSelect,onDelete,onControl}:{edge:GaiaMapEdge;nodes:GaiaMapNode[];selected:boolean;locked:boolean;onSelect:()=>void;onDelete:()=>void;onControl:(x:number,y:number)=>void}){const a=nodes.find(n=>n.id===edge.source),b=nodes.find(n=>n.id===edge.target);if(!a||!b)return null;const x1=a.x+NODE_W/2,y1=a.y+NODE_H/2,x2=b.x+NODE_W/2,y2=b.y+NODE_H/2,cx=edge.controlPoints?.[0]??(x1+x2)/2,cy=edge.controlPoints?.[1]??(y1+y2)/2,points=[x1,y1,cx,cy,x2,y2];return <Group onClick={e=>{e.cancelBubble=true;onSelect()}} onContextMenu={e=>{e.evt.preventDefault();e.cancelBubble=true;if(confirm('Apagar esta ligação?'))onDelete()}}><Arrow points={points} tension={.45} stroke={selected?'#fff':'#aebcc5'} fill={selected?'#fff':'#aebcc5'} strokeWidth={selected?6:4} hitStrokeWidth={24} pointerLength={11} pointerWidth={10}/>{edge.label&&<Text x={cx-70} y={cy-24} width={140} align="center" text={edge.label} fill="#fff" fontSize={12}/>}{selected&&!locked&&<Circle x={cx} y={cy} radius={8} fill="#ffe38b" draggable onDragMove={e=>onControl(e.target.x(),e.target.y())}/>}</Group>}
function BgShape({bg,selected,locked,onSelect,onChange}:{bg:GaiaMapBackgroundImage;selected:boolean;locked:boolean;onSelect:()=>void;onChange:(p:Partial<GaiaMapBackgroundImage>)=>void}){const [image]=useImage(mediaDisplayUrl(bg.filePath)??'','anonymous');return <KonvaImage id={cssId(bg.id)} image={image} x={bg.x} y={bg.y} width={bg.width} height={bg.height} opacity={bg.opacity} rotation={bg.rotation} draggable={!locked} stroke={selected?'#ffffff':undefined} strokeWidth={selected?3:0} onClick={e=>{e.cancelBubble=true;onSelect()}} onDragEnd={e=>onChange({x:e.target.x(),y:e.target.y()})} onTransformEnd={e=>{const n=e.target;onChange({x:n.x(),y:n.y(),width:Math.max(50,n.width()*n.scaleX()),height:Math.max(50,n.height()*n.scaleY()),rotation:n.rotation()});n.scale({x:1,y:1})}}/>}
function NodeInspector({node,project,onChange}:{node:GaiaMapNode;project:ReturnType<typeof useProjectStore.getState>['project'];onChange:(p:Partial<GaiaMapNode>)=>void}){const area=project.areas.find(a=>a.id===node.areaId);return <div className="gaia-inspector"><h3>{area?.name}</h3><label>Desbloqueio<select value={node.unlockMode??area?.unlockMode} onChange={e=>onChange({unlockMode:e.target.value as GaiaMapNode['unlockMode']})}><option value="runes">Runas</option><option value="automatico">Automático</option><option value="missao_principal">Missão principal</option><option value="inicio">Inicial</option><option value="portao_final">Portão final</option></select></label><label>Missão<select value={node.unlockMissionId??''} onChange={e=>onChange({unlockMissionId:e.target.value||undefined})}><option value="">Nenhuma</option>{project.missions.filter(m=>m.worldId===area?.worldId).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="check-row"><input type="checkbox" checked={node.worldIntro??false} onChange={e=>onChange({worldIntro:e.target.checked})}/> Apresentar mundo aqui</label><label>Notas<textarea value={node.notes??''} onChange={e=>onChange({notes:e.target.value})}/></label></div>}
function EdgeInspector({edge,onChange}:{edge:GaiaMapEdge;onChange:(p:Partial<GaiaMapEdge>)=>void}){return <div className="gaia-inspector"><h3>Ligação</h3><label>Texto<input value={edge.label} onChange={e=>onChange({label:e.target.value})}/></label><label>Tipo<select value={edge.kind??'principal'} onChange={e=>onChange({kind:e.target.value as GaiaMapEdge['kind']})}><option value="principal">Principal</option><option value="alternativa">Alternativa</option><option value="convergencia">Convergência</option></select></label><label className="check-row"><input type="checkbox" checked={edge.bidirectional??false} onChange={e=>onChange({bidirectional:e.target.checked})}/> Bidirecional</label><label>Notas<textarea value={edge.notes??''} onChange={e=>onChange({notes:e.target.value})}/></label></div>}
function BgInspector({bg,onChange}:{bg:GaiaMapBackgroundImage;onChange:(p:Partial<GaiaMapBackgroundImage>)=>void}){return <div className="gaia-inspector"><h3>Imagem</h3><label>Nome<input value={bg.name} onChange={e=>onChange({name:e.target.value})}/></label><label>Opacidade<input type="range" min=".05" max="1" step=".05" value={bg.opacity} onChange={e=>onChange({opacity:Number(e.target.value)})}/></label><button className="secondary-button" onClick={()=>onChange({locked:!bg.locked})}>{bg.locked?<Unlock/>:<Lock/>}{bg.locked?' Desbloquear':' Bloquear'}</button></div>}
function Grid({grid}:{grid:number}){const lines=[];for(let x=-4000;x<=4000;x+=grid)lines.push(<Line key={`x${x}`} points={[x,-4000,x,4000]} stroke="#7f909a" opacity={x%(grid*5)===0?.14:.05}/>);for(let y=-4000;y<=4000;y+=grid)lines.push(<Line key={`y${y}`} points={[-4000,y,4000,y]} stroke="#7f909a" opacity={y%(grid*5)===0?.14:.05}/>);return <>{lines}</>}
function unlockText(area:ReturnType<typeof useProjectStore.getState>['project']['areas'][number]|undefined){if(!area)return'';if(area.unlockMode==='runes')return`${area.accessCost} Runas`;if(area.unlockMode==='automatico')return'Automático';if(area.unlockMode==='missao_principal')return'Missão principal';if(area.unlockMode==='inicio')return'Inicial';return'Portão final'}
function layerName(k:LayerKey){return({nodes:'Nós',edges:'Ligações',images:'Imagens',drawings:'Desenhos',grid:'Grelha'} as Record<LayerKey,string>)[k]}
function screenCenter(st:Konva.Stage|null,size:{w:number;h:number}){if(!st)return{x:0,y:0};return{x:(size.w/2-st.x())/st.scaleX(),y:(size.h/2-st.y())/st.scaleY()}}
function bounds(plan:ReturnType<typeof useProjectStore.getState>['project']['worldMap']){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;const add=(x:number,y:number,w=0,h=0)=>{minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x+w);maxY=Math.max(maxY,y+h)};plan.nodes.forEach(n=>add(n.x,n.y,NODE_W,NODE_H));plan.backgroundImages.forEach(b=>add(b.x,b.y,b.width,b.height));plan.drawings.forEach(l=>{for(let i=0;i<l.points.length;i+=2)add(l.points[i],l.points[i+1])});return Number.isFinite(minX)?{x:minX,y:minY,width:Math.max(1,maxX-minX),height:Math.max(1,maxY-minY)}:null}
function nearDrawing(lines:GaiaMapDrawing[],x:number,y:number,t:number){let best:GaiaMapDrawing|undefined,d=Infinity;for(const l of lines)for(let i=0;i<l.points.length-2;i+=2){const v=dist(x,y,l.points[i],l.points[i+1],l.points[i+2],l.points[i+3]);if(v<d){d=v;best=l}}return d<=t?best:undefined}
function dist(px:number,py:number,x1:number,y1:number,x2:number,y2:number){const dx=x2-x1,dy=y2-y1,t=dx||dy?Math.max(0,Math.min(1,((px-x1)*dx+(py-y1)*dy)/(dx*dx+dy*dy))):0;return Math.hypot(px-(x1+t*dx),py-(y1+t*dy))}
function cssId(id:string){return `bg_${id.replace(/[^a-zA-Z0-9_-]/g,'_')}`}
