import { ArrowDown, ArrowUp, Plus, Trash2 } from 'lucide-react';
import { Card, Field, SectionTitle, StatusBadge } from './Ui';
import { useProjectStore } from '../store/useProjectStore';
import type { ChallengeSectionPlan } from '../types';

export function ApoloTrials(){
  const project=useProjectStore(s=>s.project),mutate=useProjectStore(s=>s.mutate);
  return <>
    <Card className="info-callout"><strong>Fluxo consolidado</strong><p>Cada mundo libera uma área de Apolo quando chega a 100%. A área não conta no percentual base. Cada conclusão entrega uma Runa de Apolo; a sexta ativa a animação das seis runas, o Emblema de Apolo e a aura de fogo. Gaia + Apolo concedem Zeus e 101%.</p></Card>
    <div className="card-grid apolo-grid">{project.apoloTrials.map(trial=><Card key={trial.id} className="apolo-trial-card"><SectionTitle>{trial.name}</SectionTitle><StatusBadge status={trial.status}/><p>{trial.description}</p><div className="form-grid three"><label className="check-row"><input type="checkbox" checked={trial.unlockedAtWorld100} onChange={e=>mutate(d=>{const t=d.apoloTrials.find(x=>x.id===trial.id);if(t)t.unlockedAtWorld100=e.target.checked})}/> Liberar no 100% do mundo</label><Field label="Runas de Apolo"><input type="number" min="1" value={trial.rewardApoloRunes} onChange={e=>mutate(d=>{const t=d.apoloTrials.find(x=>x.id===trial.id);if(t)t.rewardApoloRunes=Number(e.target.value)})}/></Field><Field label="Estado"><select value={trial.status} onChange={e=>mutate(d=>{const t=d.apoloTrials.find(x=>x.id===trial.id);if(t)t.status=e.target.value as typeof trial.status})}><option value="planejado">Planejado</option><option value="unity">Unity</option><option value="erro">Erro</option></select></Field></div><Field label="Descrição"><textarea value={trial.description} onChange={e=>mutate(d=>{const t=d.apoloTrials.find(x=>x.id===trial.id);if(t)t.description=e.target.value})}/></Field><Field label="Recompensa / aura"><textarea value={trial.auraReward??''} onChange={e=>mutate(d=>{const t=d.apoloTrials.find(x=>x.id===trial.id);if(t)t.auraReward=e.target.value})}/></Field><SectionTitle action={<button className="text-button" onClick={()=>mutate(d=>{const t=d.apoloTrials.find(x=>x.id===trial.id);if(t)t.sections.push(newSection(t.id,t.sections.length))})}><Plus/> Adicionar seção</button>}>Seções da fase</SectionTitle><div className="apolo-sections">{trial.sections.map((section,index)=><ApoloSection key={section.id} trialId={trial.id} section={section} index={index} total={trial.sections.length}/>)}</div><Field label="Notas"><textarea value={trial.notes} onChange={e=>mutate(d=>{const t=d.apoloTrials.find(x=>x.id===trial.id);if(t)t.notes=e.target.value})}/></Field></Card>)}</div>
  </>;
}

function ApoloSection({trialId,section,index,total}:{trialId:string;section:ChallengeSectionPlan;index:number;total:number}){
  const project=useProjectStore(s=>s.project),mutate=useProjectStore(s=>s.mutate);
  const patch=(data:Partial<ChallengeSectionPlan>)=>mutate(d=>{const t=d.apoloTrials.find(x=>x.id===trialId);const target=t?.sections.find(x=>x.id===section.id);if(target)Object.assign(target,data)},false,`apolo-section:${section.id}`);
  const move=(delta:number)=>mutate(d=>{const t=d.apoloTrials.find(x=>x.id===trialId);if(!t)return;const from=t.sections.findIndex(x=>x.id===section.id),to=from+delta;if(from<0||to<0||to>=t.sections.length)return;[t.sections[from],t.sections[to]]=[t.sections[to],t.sections[from]]},false,`apolo-section:move:${section.id}`);
  const toggle=(values:string[]|undefined,value:string)=>values?.includes(value)?values.filter(x=>x!==value):[...(values??[]),value];
  return <div className="apolo-section-editor"><div className="apolo-section-head"><strong>{index+1}.</strong><input value={section.name} onChange={e=>patch({name:e.target.value})}/><button className="icon-button" disabled={index===0} onClick={()=>move(-1)}><ArrowUp/></button><button className="icon-button" disabled={index===total-1} onClick={()=>move(1)}><ArrowDown/></button><button className="icon-button danger" onClick={()=>mutate(d=>{const t=d.apoloTrials.find(x=>x.id===trialId);if(t)t.sections=t.sections.filter(x=>x.id!==section.id)})}><Trash2/></button></div><Field label="Regra"><select value={section.ruleType} onChange={e=>patch({ruleType:e.target.value as ChallengeSectionPlan['ruleType']})}><option value="animal">Animal específico</option><option value="categoria">Categorias permitidas</option><option value="tempo">Tempo</option><option value="derrotar">Derrotar inimigos</option><option value="coletar">Coletar</option><option value="sobreviver">Sobreviver</option><option value="combinado">Combinada</option></select></Field>{section.ruleType==='animal'&&<Field label="Animal obrigatório"><select value={section.requiredAnimalId??''} onChange={e=>patch({requiredAnimalId:e.target.value||undefined})}><option value="">Selecione…</option>{project.animals.filter(a=>!a.isIrisBase).map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></Field>}{section.ruleType==='categoria'&&<Field label="Categorias permitidas"><div className="chips selectable">{['Rápido','Saltador','Escalador','Forte','Predador','Voador','Aquático','Furtivo','Resistente'].map(c=><button className={(section.requiredCategories??[]).includes(c)?'selected':''} key={c} onClick={()=>patch({requiredCategories:toggle(section.requiredCategories,c)})}>{c}</button>)}</div></Field>}{section.ruleType==='tempo'&&<Field label="Limite em segundos"><input type="number" min="1" value={section.timeLimitSeconds??60} onChange={e=>patch({timeLimitSeconds:Number(e.target.value)})}/></Field>}{section.ruleType==='derrotar'&&<Field label="Quantidade de inimigos"><input type="number" min="0" value={section.enemyCount??0} onChange={e=>patch({enemyCount:Number(e.target.value)})}/></Field>}{section.ruleType==='coletar'&&<Field label="Alvo de coleta"><input value={section.collectTarget??''} placeholder="Todas as Sementes, uma Runa, item específico…" onChange={e=>patch({collectTarget:e.target.value})}/></Field>}<Field label="Descrição e regras"><textarea value={section.description} onChange={e=>patch({description:e.target.value})}/></Field></div>;
}

function newSection(parent:string,index:number):ChallengeSectionPlan{return{id:`${parent}-section-${crypto.randomUUID()}`,name:`Seção ${index+1}`,ruleType:'combinado',description:'Defina as regras desta seção.'};}
