import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Boxes, CheckCircle2, CircleDot, Flag, Heart, MapPin, Plus, ScrollText, Shield, Signpost, StickyNote, Warehouse } from 'lucide-react';
import { Card, Field, SectionTitle } from './Ui';
import { EntityTools } from './EntityTools';
import { useProjectStore } from '../store/useProjectStore';
import type { AreaResourceDef, AreaResourceKind, EntityStatus, MapObject } from '../types';

const kinds:Array<{id:AreaResourceKind;label:string;icon:React.ReactNode;color:string}>=[
  {id:'rune',label:'Runas',icon:<CircleDot/>,color:'#d9b34c'},{id:'chest',label:'Baús',icon:<Boxes/>,color:'#b77945'},{id:'fragment',label:'Fragmentos Vitais',icon:<Heart/>,color:'#e66c79'},
  {id:'missionObject',label:'Objetos de missão',icon:<ScrollText/>,color:'#8a77d6'},{id:'missionPoint',label:'Pontos invisíveis',icon:<MapPin/>,color:'#ffc857'},{id:'checkpoint',label:'Checkpoints',icon:<Flag/>,color:'#70b7e6'},
  {id:'exit',label:'Saídas',icon:<Signpost/>,color:'#63c6a3'},{id:'safeHaven',label:'Refúgios Seguros',icon:<Shield/>,color:'#6da7ff'},{id:'levelNote',label:'Notas de level design',icon:<StickyNote/>,color:'#e7c76e'},{id:'narrativeObject',label:'Objetos narrativos',icon:<Warehouse/>,color:'#b882d8'},
];
export function AreaResourcesPanel({areaId}:{areaId:string}){
  const project=useProjectStore(s=>s.project),mutate=useProjectStore(s=>s.mutate);
  const [createKind,setCreateKind]=useState<AreaResourceKind>('chest'),[createCount,setCreateCount]=useState(1),[filter,setFilter]=useState<'all'|AreaResourceKind>('all');
  const area=project.areas.find(a=>a.id===areaId),map=project.maps.find(m=>m.areaId===areaId);
  const resources=project.areaResources.filter(r=>r.areaId===areaId&&!r.archived);
  const rows=useMemo(()=>filter==='all'?resources:resources.filter(r=>r.kind===filter),[resources,filter]);
  const create=()=>mutate(d=>{for(let i=0;i<Math.max(1,Math.min(50,createCount));i++){const meta=kinds.find(k=>k.id===createKind)!;const current=d.areaResources.filter(r=>r.areaId===areaId&&r.kind===createKind).length;d.areaResources.push({id:`${createKind}-${areaId}-${crypto.randomUUID()}`,areaId,kind:createKind,name:`${singular(meta.label)} ${current+i+1}`,description:'',status:'planejado',notes:'',archived:false})}},false,`resources:create:${areaId}`);
  const patch=(id:string,data:Partial<AreaResourceDef>)=>mutate(d=>{const r=d.areaResources.find(x=>x.id===id);if(r)Object.assign(r,data)},false,`resource:${id}`);
  const prepareMap=(resource:AreaResourceDef)=>mutate(d=>{const r=d.areaResources.find(x=>x.id===resource.id),m=d.maps.find(x=>x.areaId===areaId);if(!r||!m)return;let object=r.mapObjectId?m.objects.find(o=>o.id===r.mapObjectId):undefined;if(!object){object=toMapObject(r);m.objects.push(object);r.mapObjectId=object.id}else object.archived=false},false,`resource-map:${resource.id}`);
  if(!area||!map)return null;
  return <div className="area-resources-v2">
    <div className="resource-creator"><Field label="Tipo"><select value={createKind} onChange={e=>setCreateKind(e.target.value as AreaResourceKind)}>{kinds.map(k=><option key={k.id} value={k.id}>{k.label}</option>)}</select></Field><Field label="Quantidade"><input type="number" min="1" max="50" value={createCount} onChange={e=>setCreateCount(Number(e.target.value))}/></Field><button className="primary-button" onClick={create}><Plus/> Criar recursos</button></div>
    <div className="resource-kind-grid">{kinds.map(k=>{const count=resources.filter(r=>r.kind===k.id).length,placed=resources.filter(r=>r.kind===k.id&&r.mapObjectId&&map.objects.some(o=>o.id===r.mapObjectId&&o.placed!==false&&!o.archived)).length;return <button key={k.id} className={filter===k.id?'active':''} style={{'--resource-color':k.color} as React.CSSProperties} onClick={()=>setFilter(filter===k.id?'all':k.id)}>{k.icon}<span><strong>{count}</strong>{k.label}</span><small>{placed} no mapa</small></button>})}</div>
    <Card><SectionTitle>Recursos criados — {rows.length}</SectionTitle>{rows.length===0?<div className="empty-state">Nenhum recurso deste tipo foi criado.</div>:<div className="resource-table"><div className="resource-table-head"><span>Recurso</span><span>Estado</span><span>Zona</span><span>Mapa</span><span>Relações e ações</span></div>{rows.map(resource=>{const object=resource.mapObjectId?map.objects.find(o=>o.id===resource.mapObjectId):undefined;return <div className="resource-table-row" key={resource.id}><div><input value={resource.name} onChange={e=>patch(resource.id,{name:e.target.value})}/><small>{kinds.find(k=>k.id===resource.kind)?.label} · {resource.id}</small></div><select value={resource.status} onChange={e=>patch(resource.id,{status:e.target.value as EntityStatus})}><option value="planejado">Planejado</option><option value="unity">Unity</option><option value="erro">Erro</option></select><input value={resource.zoneId??''} onChange={e=>patch(resource.id,{zoneId:e.target.value||undefined})} placeholder="Sem zona"/><div className={object?.placed!==false&&object&&!object.archived?'map-state placed':'map-state'}>{object?.placed!==false&&object&&!object.archived?<><CheckCircle2/> Colocado</>:<><MapPin/> Fora do mapa</>}</div><div className="resource-actions">{object?<Link className="icon-button" title="Abrir centralizado no mapa" to={`/area/${areaId}/map?object=${object.id}`}><MapPin/></Link>:<button className="icon-button" title="Preparar para colocar no mapa" onClick={()=>prepareMap(resource)}><Plus/></button>}<EntityTools entityRef={{type:'areaResource',id:resource.id,parentId:areaId}} compact/></div></div>})}</div>}</Card>
    <Card><SectionTitle>Detalhes do recurso selecionado</SectionTitle><p className="muted">Abra a Central de Relações pela ação de cada linha. Pontos de missão podem ser associados a uma missão e tarefa na própria ficha ou no criador de missões.</p>{rows.slice(0,1).map(resource=><div key={resource.id} className="resource-detail-grid"><Field label="Descrição"><textarea value={resource.description} onChange={e=>patch(resource.id,{description:e.target.value})}/></Field><Field label="Missão"><select value={resource.missionId??''} onChange={e=>patch(resource.id,{missionId:e.target.value||undefined,taskId:undefined})}><option value="">Nenhuma</option>{project.missions.filter(m=>m.areaIds.includes(areaId)||m.suggestedAreaId===areaId).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label="Tarefa"><select value={resource.taskId??''} onChange={e=>patch(resource.id,{taskId:e.target.value||undefined})}><option value="">Nenhuma</option>{project.missions.find(m=>m.id===resource.missionId)?.tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></Field>{resource.kind==='exit'&&<Field label="Área de destino"><select value={resource.targetAreaId??''} onChange={e=>patch(resource.id,{targetAreaId:e.target.value||undefined})}><option value="">Não definida</option>{project.areas.filter(a=>a.id!==areaId).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field>}<Field label="Notas"><textarea value={resource.notes} onChange={e=>patch(resource.id,{notes:e.target.value})}/></Field></div>)}</Card>
  </div>;
}
function toMapObject(r:AreaResourceDef):MapObject{const meta=kinds.find(k=>k.id===r.kind)!;const resourceType=r.kind==='rune'?'rune':r.kind==='chest'?'chest':r.kind==='fragment'?'fragment':'mission';return{id:`map-${r.id}`,type:r.kind==='missionPoint'?'missionPoint':r.kind==='levelNote'?'note':r.kind==='exit'?'entry':'resource',x:0,y:0,label:r.name,resourceType,resourceId:r.id,icon:iconFor(r.kind),status:r.status,zoneId:r.zoneId,categoryColor:meta.color,placed:false,relationIds:[r.missionId,r.taskId,r.targetAreaId].filter(Boolean) as string[]}}
function iconFor(k:AreaResourceKind){return({rune:'◆',chest:'▣',fragment:'♥',missionObject:'◇',missionPoint:'●',checkpoint:'⚑',exit:'⇥',safeHaven:'⌂',levelNote:'T',narrativeObject:'✦'} as Record<AreaResourceKind,string>)[k]}
function singular(s:string){return s.endsWith('s')?s.slice(0,-1):s}
