import { useState } from 'react';
import { ArrowDown, ArrowUp, Eye, ImagePlus, Replace, Star } from 'lucide-react';
import { mediaDisplayUrl, persistMediaFile } from '../lib/storage';
import { useProjectStore } from '../store/useProjectStore';
import type { GalleryImage } from '../types';
import { EntityTools } from './EntityTools';

export function GalleryManager({ownerType,ownerId}:{ownerType:GalleryImage['ownerType'];ownerId:string}){
  const project=useProjectStore(s=>s.project),mutate=useProjectStore(s=>s.mutate),[preview,setPreview]=useState<string>();
  const images=project.galleryImages.filter(i=>i.ownerType===ownerType&&i.ownerId===ownerId&&!i.archived).sort((a,b)=>a.order-b.order);
  const map=ownerType==='area'?project.maps.find(m=>m.areaId===ownerId):undefined;
  const zones=map?.objects.filter(o=>o.type==='zone').map(o=>({id:o.id,name:o.label||o.id}))??[];
  const add=async(files:FileList|null)=>{for(const file of [...(files??[])]){const saved=await persistMediaFile(file,`${ownerType}s/${ownerId}/gallery`);mutate(d=>d.galleryImages.push({id:crypto.randomUUID(),ownerType,ownerId,filePath:saved,caption:'',kind:'referencia',primary:false,order:d.galleryImages.filter(i=>i.ownerType===ownerType&&i.ownerId===ownerId).length,archived:false}),false,`gallery:add:${ownerId}`)}};
  const patch=(id:string,p:Partial<GalleryImage>)=>mutate(d=>{const i=d.galleryImages.find(x=>x.id===id);if(i){if(p.primary)for(const other of d.galleryImages)if(other.ownerType===ownerType&&other.ownerId===ownerId)other.primary=false;Object.assign(i,p)}},false,`gallery:${id}`);
  const replace=async(image:GalleryImage,file:File)=>{const saved=await persistMediaFile(file,`${ownerType}s/${ownerId}/gallery`);patch(image.id,{filePath:saved})};
  const move=(index:number,delta:number)=>mutate(d=>{const list=d.galleryImages.filter(i=>i.ownerType===ownerType&&i.ownerId===ownerId&&!i.archived).sort((a,b)=>a.order-b.order),j=index+delta;if(j<0||j>=list.length)return;const a=list[index],b=list[j],temp=a.order;a.order=b.order;b.order=temp},false,`gallery:order:${ownerId}`);
  return <div className="gallery-manager"><label className="upload-zone"><input type="file" accept="image/*" multiple onChange={e=>void add(e.target.files)}/><ImagePlus/><span>Adicionar imagens à galeria</span></label>{images.length===0&&<div className="empty-state">Nenhuma imagem adicionada.</div>}<div className="gallery-manager-grid">{images.map((image,index)=><div className={`gallery-manager-card ${image.primary?'primary':''}`} key={image.id}><div className="gallery-image-wrap"><img src={mediaDisplayUrl(image.filePath)} alt={image.caption||'Imagem da galeria'}/><div className="gallery-image-actions"><button className="icon-button" onClick={()=>setPreview(image.filePath)} title="Abrir em tela cheia"><Eye/></button><button className="icon-button" title="Definir como principal" onClick={()=>patch(image.id,{primary:true})}><Star/></button><label className="icon-button file-button" title="Substituir arquivo"><Replace/><input type="file" accept="image/*" onChange={e=>{const file=e.target.files?.[0];if(file)void replace(image,file)}}/></label></div>{image.primary&&<span className="primary-badge">Principal</span>}</div><input placeholder="Legenda" value={image.caption} onChange={e=>patch(image.id,{caption:e.target.value})}/><select value={image.kind} onChange={e=>patch(image.id,{kind:e.target.value as GalleryImage['kind']})}><option value="puzzle">Puzzle</option><option value="conceito">Conceito</option><option value="referencia">Referência</option><option value="tileset">Tileset</option><option value="fluxo">Fluxo</option></select><div className="form-grid"><select value={image.mechanicId??''} onChange={e=>patch(image.id,{mechanicId:e.target.value||undefined})}><option value="">Sem mecânica relacionada</option>{project.mechanics.filter(m=>!m.archived).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select>{ownerType==='area'?<select value={image.zoneId??''} onChange={e=>patch(image.id,{zoneId:e.target.value||undefined})}><option value="">Sem zona</option>{zones.map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select>:<input placeholder="Zona ou contexto" value={image.zoneId??''} onChange={e=>patch(image.id,{zoneId:e.target.value||undefined})}/>}</div><div className="gallery-card-footer"><button className="icon-button" disabled={index===0} onClick={()=>move(index,-1)}><ArrowUp/></button><button className="icon-button" disabled={index===images.length-1} onClick={()=>move(index,1)}><ArrowDown/></button><EntityTools compact entityRef={{type:'galleryImage',id:image.id,parentId:ownerId}}/></div></div>)}</div>{preview&&<div className="modal-backdrop" onClick={()=>setPreview(undefined)}><div className="image-preview"><img src={mediaDisplayUrl(preview)} alt="Pré-visualização"/><button className="secondary-button" onClick={()=>setPreview(undefined)}>Fechar</button></div></div>}</div>;
}
